import Compiler.CompilationModel.ParamLoading
import Verity.Core.Model.DynamicAbi

namespace Compiler.Proofs.IRGeneration

open Compiler
open Compiler.CompilationModel

namespace DynamicAbiRefinement

/-- Byte size of selector-prefixed external calldata represented by Verity's
    transaction model: one selector word prefix plus ABI words in `calldata`. -/
def externalCalldataSize (calldata : List Nat) : Nat :=
  4 + 32 * calldata.length

/-- Bounds-checked external `calldataload` relation. The operational model
    still zero-pads arbitrary EVM reads; decoder refinement uses this checked
    relation because generated dynamic ABI loaders revert before reading words
    outside the semantic ABI payload. -/
def externalWordAt? (selector : Nat) (calldata : List Nat) (byteOffset : Nat) :
    Option Nat :=
  if 4 ≤ byteOffset ∧ byteOffset + 32 ≤ externalCalldataSize calldata then
    some (Compiler.CompilationModel.DynamicAbi.calldataloadWord selector calldata byteOffset)
  else
    none

inductive DynamicPayloadShape where
  | bytesLike
  | array (elementStrideWords : Nat)
  deriving Repr, DecidableEq

def DynamicPayloadShape.fitsLength (shape : DynamicPayloadShape)
    (length tailRemaining : Nat) : Bool :=
  match shape with
  | .bytesLike => length ≤ tailRemaining
  | .array elementStrideWords =>
      length ≤ tailRemaining / (32 * Nat.max 1 elementStrideWords)

/-- Semantic counterpart of `genDynamicParamLoads` for length-prefixed dynamic
    external ABI parameters (`bytes`, `string`, and dynamic arrays). Field names
    mirror generated Yul bindings such as `{name}_offset`, `{name}_length`, and
    `{name}_data_offset`. -/
structure LengthPrefixedDynamicParam where
  relativeOffset : Nat
  absoluteOffset : Nat
  length : Nat
  tailHeadEnd : Nat
  tailRemaining : Nat
  dataOffset : Nat
  deriving Repr, DecidableEq

/-- Decode one length-prefixed dynamic external parameter head into the binding
    values generated by `genDynamicParamLoads`.

    Parameters:
    * `headSize`: total ABI head size in bytes, excluding the selector.
    * `baseOffset`: byte offset of the ABI tuple head (`4` for external calls).
    * `headOffset`: absolute byte offset of this parameter's head word. -/
def decodeLengthPrefixedDynamicParam? (selector : Nat) (calldata : List Nat)
    (shape : DynamicPayloadShape) (headSize baseOffset headOffset : Nat) :
    Option LengthPrefixedDynamicParam := do
  let relativeOffset ← externalWordAt? selector calldata headOffset
  if relativeOffset < headSize then
    none
  else
    let absoluteOffset := baseOffset + relativeOffset
    if absoluteOffset + 32 > externalCalldataSize calldata then
      none
    else
      let length ← externalWordAt? selector calldata absoluteOffset
      let tailHeadEnd := absoluteOffset + 32
      let tailRemaining := externalCalldataSize calldata - tailHeadEnd
      if shape.fitsLength length tailRemaining then
        some
          { relativeOffset := relativeOffset
            absoluteOffset := absoluteOffset
            length := length
            tailHeadEnd := tailHeadEnd
            tailRemaining := tailRemaining
            dataOffset := tailHeadEnd }
      else
        none

/-- Semantic counterpart of dynamic-tuple parameter loading. Dynamic tuple
    pointers target the tuple head directly and therefore bind `{name}_data_offset`
    to the absolute offset, without skipping a length word. -/
def decodeDynamicTupleParamDataOffset? (selector : Nat) (calldata : List Nat)
    (headSize baseOffset headOffset : Nat) : Option Nat := do
  let relativeOffset ← externalWordAt? selector calldata headOffset
  if relativeOffset < headSize then
    none
  else
    let absoluteOffset := baseOffset + relativeOffset
    if absoluteOffset + 32 ≤ externalCalldataSize calldata then
      some absoluteOffset
    else
      none

/-- Resolve the head offset of a dynamically encoded array element, matching
    `checkedArrayElementDynamicDataOffsetCalldataHelper`. -/
def arrayElementDynamicHeadOffset? (selector : Nat) (calldata : List Nat)
    (dataOffset length index : Nat) : Option Nat := do
  if index < length then
    let offsetTableBytes := length * 32
    let elementRelOffset ←
      externalWordAt? selector calldata (dataOffset + index * 32)
    if elementRelOffset < offsetTableBytes then
      none
    else
      let elementHead := dataOffset + elementRelOffset
      if elementHead + 32 ≤ externalCalldataSize calldata then
        some elementHead
      else
        none
  else
    none

theorem arrayElementDynamicHeadOffset?_index_oob
    (selector : Nat) (calldata : List Nat) (dataOffset length index : Nat)
    (h : length ≤ index) :
    arrayElementDynamicHeadOffset? selector calldata dataOffset length index = none := by
  unfold arrayElementDynamicHeadOffset?
  simp [Nat.not_lt.mpr h]

/-- Read a word from the head of a dynamically encoded array element, matching
    `checkedArrayElementDynamicWordCalldataHelper`. -/
def arrayElementDynamicWord? (selector : Nat) (calldata : List Nat)
    (dataOffset length index wordOffset : Nat) : Option Nat := do
  let elementHead ← arrayElementDynamicHeadOffset? selector calldata dataOffset length index
  externalWordAt? selector calldata (elementHead + wordOffset * 32)

/-- Resolve a dynamic member's length word inside a dynamically encoded array
    element, matching `checkedArrayElementDynamicMemberLengthCalldataHelper`. -/
def arrayElementDynamicMemberLength? (selector : Nat) (calldata : List Nat)
    (dataOffset length index wordOffset : Nat) : Option Nat := do
  let elementHead ← arrayElementDynamicHeadOffset? selector calldata dataOffset length index
  let memberRelOffset ← externalWordAt? selector calldata (elementHead + wordOffset * 32)
  let memberDataPos := elementHead + memberRelOffset
  externalWordAt? selector calldata memberDataPos

/-- Resolve the data offset of a dynamic member inside a dynamically encoded
    array element, matching `checkedArrayElementDynamicMemberDataOffsetCalldataHelper`. -/
def arrayElementDynamicMemberDataOffset? (selector : Nat) (calldata : List Nat)
    (dataOffset length index wordOffset : Nat) : Option Nat := do
  let elementHead ← arrayElementDynamicHeadOffset? selector calldata dataOffset length index
  let memberRelOffset ← externalWordAt? selector calldata (elementHead + wordOffset * 32)
  let memberDataPos := elementHead + memberRelOffset
  if memberDataPos + 32 ≤ externalCalldataSize calldata then
    some (memberDataPos + 32)
  else
    none

def arrayElementDynamicMemberElement? (selector : Nat) (calldata : List Nat)
    (dataOffset length index wordOffset innerIndex : Nat) : Option Nat := do
  let memberLength ←
    arrayElementDynamicMemberLength? selector calldata dataOffset length index wordOffset
  if innerIndex < memberLength then
    let memberDataOffset ←
      arrayElementDynamicMemberDataOffset? selector calldata dataOffset length index wordOffset
    externalWordAt? selector calldata (memberDataOffset + innerIndex * 32)
  else
    none

theorem arrayElementDynamicMemberDataOffset_eq_length_pos_add_word
    {selector : Nat} {calldata : List Nat} {dataOffset length index wordOffset data : Nat}
    (h :
      arrayElementDynamicMemberDataOffset? selector calldata dataOffset length index wordOffset =
        some data) :
    ∃ elementHead memberRelOffset,
      arrayElementDynamicHeadOffset? selector calldata dataOffset length index = some elementHead ∧
      externalWordAt? selector calldata (elementHead + wordOffset * 32) = some memberRelOffset ∧
      data = elementHead + memberRelOffset + 32 := by
  unfold arrayElementDynamicMemberDataOffset? at h
  cases hhead :
      arrayElementDynamicHeadOffset? selector calldata dataOffset length index with
  | none => simp [hhead] at h
  | some elementHead =>
      cases hmember :
          externalWordAt? selector calldata (elementHead + wordOffset * 32) with
      | none => simp [hhead, hmember] at h
      | some memberRelOffset =>
          by_cases hbounds :
              elementHead + memberRelOffset + 32 ≤ externalCalldataSize calldata
          · simp [hhead, hmember, hbounds] at h
            refine ⟨elementHead, memberRelOffset, ?_, ?_, ?_⟩
            · rfl
            · simp [hmember]
            · exact h.symm
          · simp [hhead, hmember, hbounds] at h

/-! ## ERC-4337 `PackedUserOperation[]` acceptance surface -/

namespace ERC4337

/-- Selector for
    `handleOps((address,uint256,bytes,bytes,bytes32,uint256,bytes32,bytes,bytes)[],address)`. -/
def handleOpsSelector : Nat := 0x765e827f

/-- `PackedUserOperation` ABI head word count in EntryPoint v0.9:
    sender, nonce, initCode, callData, accountGasLimits,
    preVerificationGas, gasFees, paymasterAndData, signature. -/
def packedUserOperationHeadWords : Nat := 9

def initCodeWordOffset : Nat := 2
def callDataWordOffset : Nat := 3
def paymasterAndDataWordOffset : Nat := 7
def signatureWordOffset : Nat := 8

def handleOpsHeadSize : Nat := 64
def handleOpsOpsHeadOffset : Nat := 4
def handleOpsBeneficiaryHeadOffset : Nat := 36
def externalAbiBaseOffset : Nat := 4

def decodeOpsParam? (selector : Nat) (calldata : List Nat) :
    Option LengthPrefixedDynamicParam :=
  decodeLengthPrefixedDynamicParam? selector calldata
    (.array 1) handleOpsHeadSize externalAbiBaseOffset handleOpsOpsHeadOffset

def beneficiaryWord? (selector : Nat) (calldata : List Nat) : Option Nat :=
  externalWordAt? selector calldata handleOpsBeneficiaryHeadOffset

structure PackedUserOperationDynamicBytes where
  length : Nat
  dataOffset : Nat
  deriving Repr, DecidableEq

def decodePackedUserOperationBytesMember? (selector : Nat) (calldata : List Nat)
    (ops : LengthPrefixedDynamicParam) (index wordOffset : Nat) :
    Option PackedUserOperationDynamicBytes := do
  let length ←
    arrayElementDynamicMemberLength? selector calldata ops.dataOffset ops.length index wordOffset
  let dataOffset ←
    arrayElementDynamicMemberDataOffset? selector calldata ops.dataOffset ops.length index wordOffset
  some { length := length, dataOffset := dataOffset }

structure PackedUserOperationAbiView where
  sender : Nat
  nonce : Nat
  accountGasLimits : Nat
  preVerificationGas : Nat
  gasFees : Nat
  initCode : PackedUserOperationDynamicBytes
  callData : PackedUserOperationDynamicBytes
  paymasterAndData : PackedUserOperationDynamicBytes
  signature : PackedUserOperationDynamicBytes
  deriving Repr, DecidableEq

def decodePackedUserOperationAt? (selector : Nat) (calldata : List Nat)
    (ops : LengthPrefixedDynamicParam) (index : Nat) :
    Option PackedUserOperationAbiView := do
  let sender ← arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 0
  let nonce ← arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 1
  let accountGasLimits ← arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 4
  let preVerificationGas ← arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 5
  let gasFees ← arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 6
  let initCode ←
    decodePackedUserOperationBytesMember? selector calldata ops index initCodeWordOffset
  let callData ←
    decodePackedUserOperationBytesMember? selector calldata ops index callDataWordOffset
  let paymasterAndData ←
    decodePackedUserOperationBytesMember? selector calldata ops index paymasterAndDataWordOffset
  let signature ←
    decodePackedUserOperationBytesMember? selector calldata ops index signatureWordOffset
  some
    { sender := sender
      nonce := nonce
      accountGasLimits := accountGasLimits
      preVerificationGas := preVerificationGas
      gasFees := gasFees
      initCode := initCode
      callData := callData
      paymasterAndData := paymasterAndData
      signature := signature }

theorem decodePackedUserOperationAt?_dynamic_bytes_members
    {selector : Nat} {calldata : List Nat} {ops : LengthPrefixedDynamicParam}
    {index : Nat} {view : PackedUserOperationAbiView}
    (h : decodePackedUserOperationAt? selector calldata ops index = some view) :
    decodePackedUserOperationBytesMember? selector calldata ops index initCodeWordOffset =
        some view.initCode ∧
      decodePackedUserOperationBytesMember? selector calldata ops index callDataWordOffset =
        some view.callData ∧
      decodePackedUserOperationBytesMember? selector calldata ops index paymasterAndDataWordOffset =
        some view.paymasterAndData ∧
      decodePackedUserOperationBytesMember? selector calldata ops index signatureWordOffset =
        some view.signature := by
  unfold decodePackedUserOperationAt? at h
  cases hsender :
      arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 0 with
  | none => simp [hsender] at h
  | some sender =>
      cases hnonce :
          arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 1 with
      | none => simp [hsender, hnonce] at h
      | some nonce =>
          cases haccountGasLimits :
              arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 4 with
          | none => simp [hsender, hnonce, haccountGasLimits] at h
          | some accountGasLimits =>
              cases hpreVerificationGas :
                  arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 5 with
              | none => simp [hsender, hnonce, haccountGasLimits, hpreVerificationGas] at h
              | some preVerificationGas =>
                  cases hgasFees :
                      arrayElementDynamicWord? selector calldata ops.dataOffset ops.length index 6 with
                  | none =>
                      simp [hsender, hnonce, haccountGasLimits, hpreVerificationGas, hgasFees] at h
                  | some gasFees =>
                      cases hinit :
                          decodePackedUserOperationBytesMember?
                            selector calldata ops index initCodeWordOffset with
                      | none =>
                          simp [hsender, hnonce, haccountGasLimits, hpreVerificationGas,
                            hgasFees, hinit] at h
                      | some initCode =>
                          cases hcall :
                              decodePackedUserOperationBytesMember?
                                selector calldata ops index callDataWordOffset with
                          | none =>
                              simp [hsender, hnonce, haccountGasLimits, hpreVerificationGas,
                                hgasFees, hinit, hcall] at h
                          | some callData =>
                              cases hpaymaster :
                                  decodePackedUserOperationBytesMember?
                                    selector calldata ops index paymasterAndDataWordOffset with
                              | none =>
                                  simp [hsender, hnonce, haccountGasLimits, hpreVerificationGas,
                                    hgasFees, hinit, hcall, hpaymaster] at h
                              | some paymasterAndData =>
                                  cases hsignature :
                                      decodePackedUserOperationBytesMember?
                                        selector calldata ops index signatureWordOffset with
                                  | none =>
                                      simp [hsender, hnonce, haccountGasLimits,
                                        hpreVerificationGas, hgasFees, hinit, hcall,
                                        hpaymaster, hsignature] at h
                                  | some signature =>
                                      simp [hsender, hnonce, haccountGasLimits,
                                        hpreVerificationGas, hgasFees, hinit, hcall,
                                        hpaymaster, hsignature] at h
                                      cases h
                                      exact ⟨rfl, rfl, rfl, rfl⟩

structure HandleOpsAbiView where
  ops : LengthPrefixedDynamicParam
  beneficiary : Nat
  deriving Repr, DecidableEq

def decodeHandleOps? (selector : Nat) (calldata : List Nat) :
    Option HandleOpsAbiView := do
  let ops ← decodeOpsParam? selector calldata
  let beneficiary ← beneficiaryWord? selector calldata
  some { ops := ops, beneficiary := beneficiary }

theorem decodeHandleOps_ops_binding
    {selector : Nat} {calldata : List Nat} {view : HandleOpsAbiView}
    (h : decodeHandleOps? selector calldata = some view) :
    decodeOpsParam? selector calldata = some view.ops := by
  unfold decodeHandleOps? at h
  cases hops : decodeOpsParam? selector calldata with
  | none => simp [hops] at h
  | some ops =>
      cases hbeneficiary : beneficiaryWord? selector calldata <;> simp [hops, hbeneficiary] at h
      cases h
      rfl

end ERC4337

end DynamicAbiRefinement

end Compiler.Proofs.IRGeneration
