import Compiler.Proofs.AbiEncoding
import Compiler.Proofs.IRGeneration.EventObservable
import Compiler.Proofs.YulGeneration.Calldata

/-!
# ABI argument blocks in memory (#2082 slice 3)

Slices 1 and 2 (`Compiler/Proofs/AbiEncoding.lean`) specify ABI argument
blocks as *words*: `abiEncodeScalarHeads` for the static scalar case and
`abiEncodeArgs` (heads, dynamic heads carrying block-relative tail offsets,
then tails) for the dynamic case.  Nothing so far connects those words to the
memory an `mstore` block actually leaves behind.

This module closes that gap.  `abiBlockWrites` is the write list that lays a
word sequence out at 32-byte stride from a base pointer, and
`yulLogDataWords_abiBlockWrites` reads it back: under the no-wrap bound the
block is exactly the written words, in order.  Instantiating that at the two
slice encoders gives the layout theorems
`abiEncodeScalarHeads_memory_layout` and `abiEncodeArgs_memory_layout`, and
the pointwise corollaries pin the ABI-spec facts individually — head area
size, each head word, and the dynamic tail offset carried in a dynamic head
(`abiEncodeArgs_memory_dynamic_offset_points_at_tail`).

Readback is stated with `yulLogDataWords`, the word-granular payload the
proof IR records for a `log*` instruction, so these theorems compose directly
with the emit lane in `AbiEventObservable.lean`.
-/

namespace Compiler.Proofs.AbiMemoryLayout

open Compiler
open Compiler.Yul
open Compiler.CompilationModel
open Compiler.Proofs.AbiEncoding
open Compiler.Proofs.IRGeneration

/-! ## Word-block writes -/

/-- The `mstore` write list laying `words` out consecutively, one 32-byte ABI
word per entry, starting at byte address `base`. -/
def abiBlockWrites (base : Nat) : List Nat → List (Nat × Nat)
  | [] => []
  | word :: rest =>
      (base % Compiler.Constants.evmModulus, word) :: abiBlockWrites (base + 32) rest

@[simp] theorem abiBlockWrites_nil (base : Nat) : abiBlockWrites base [] = [] := rfl

@[simp] theorem abiBlockWrites_cons (base word : Nat) (rest : List Nat) :
    abiBlockWrites base (word :: rest) =
      (base % Compiler.Constants.evmModulus, word) :: abiBlockWrites (base + 32) rest := rfl

@[simp] theorem abiBlockWrites_length (base : Nat) (words : List Nat) :
    (abiBlockWrites base words).length = words.length := by
  induction words generalizing base with
  | nil => rfl
  | cons _ rest ih => simp [ih]

/-- Positional view of the write list: entry `i` targets `base + i * 32`.  This
is the form produced by pointer-offset `mstore` blocks, whose store offsets are
generated by index. -/
theorem abiBlockWrites_eq_zip :
    ∀ (words : List Nat) (base : Nat),
      abiBlockWrites base words =
        ((List.range words.length).map
          (fun i => (base + i * 32) % Compiler.Constants.evmModulus)).zip words
  | [], _ => rfl
  | word :: rest, base => by
      rw [abiBlockWrites_cons, abiBlockWrites_eq_zip rest (base + 32)]
      simp only [List.length_cons, List.range_succ_eq_map, List.map_cons, List.map_map,
        List.zip_cons_cons, Nat.zero_mul, Nat.add_zero, List.cons.injEq, true_and]
      congr 1
      apply List.map_congr_left
      intro i _
      simp only [Function.comp_apply]
      congr 1
      omega

/-- A block that fits below `2 ^ 256` writes only at addresses from `base`
upward, so no entry can alias an earlier one. -/
private theorem abiBlockWrites_key_ge :
    ∀ (words : List Nat) (base : Nat),
      base + 32 * words.length ≤ Compiler.Constants.evmModulus →
      ∀ ow ∈ abiBlockWrites base words, base ≤ ow.1 := by
  intro words
  induction words with
  | nil => intro base _ ow hmem; simp at hmem
  | cons word rest ih =>
      intro base hfit ow hmem
      have hbase : base < Compiler.Constants.evmModulus := by
        simp only [List.length_cons] at hfit
        omega
      simp only [abiBlockWrites_cons, List.mem_cons] at hmem
      rcases hmem with rfl | hmem
      · simp [Nat.mod_eq_of_lt hbase]
      · have hfit' : base + 32 + 32 * rest.length ≤ Compiler.Constants.evmModulus := by
          simp only [List.length_cons] at hfit
          omega
        have := ih (base + 32) hfit' ow hmem
        omega

/-- Later writes shadow earlier ones, so a key that no later write touches
reads back the value written at its own position. -/
theorem applyWrites_hit (k word : Nat) :
    ∀ (pre post : List (Nat × Nat)) (mem : Nat → Nat),
      (∀ ow ∈ post, ow.1 ≠ k) →
      applyWrites mem (pre ++ (k, word) :: post) k = word
  | [], post, mem, hpost => by
      rw [List.nil_append,
        show applyWrites mem ((k, word) :: post) k =
          applyWrites (fun x => if x = k then word else mem x) post k from rfl,
        applyWrites_not_written k post _ hpost]
      simp
  | (o, v) :: rest, post, mem, hpost => by
      rw [List.cons_append,
        show applyWrites mem ((o, v) :: (rest ++ (k, word) :: post)) k =
          applyWrites (fun x => if x = o then v else mem x)
            (rest ++ (k, word) :: post) k from rfl,
        applyWrites_hit k word rest post _ hpost]

/-- The first slot of a block survives the rest of the block, because every
later write lands at least 32 bytes higher. -/
theorem applyWrites_abiBlockWrites_head (word : Nat) (rest : List Nat) (base : Nat)
    (mem : Nat → Nat)
    (hfit : base + 32 + 32 * rest.length ≤ Compiler.Constants.evmModulus) :
    applyWrites mem (abiBlockWrites base (word :: rest))
        (base % Compiler.Constants.evmModulus) = word := by
  have hbase : base < Compiler.Constants.evmModulus := by omega
  have hkeys : ∀ ow ∈ abiBlockWrites (base + 32) rest,
      ow.1 ≠ base % Compiler.Constants.evmModulus := by
    intro ow hmem
    have := abiBlockWrites_key_ge rest (base + 32) hfit ow hmem
    rw [Nat.mod_eq_of_lt hbase]
    omega
  simpa using
    applyWrites_hit (base % Compiler.Constants.evmModulus) word []
      (abiBlockWrites (base + 32) rest) mem hkeys

/-- **Memory layout of a word block.**  Reading `words.length` consecutive
words back from `base` returns exactly the words written, provided the block
does not wrap the 256-bit address space. -/
theorem yulLogDataWords_abiBlockWrites :
    ∀ (words : List Nat) (base : Nat) (mem : Nat → Nat),
      base + 32 * words.length ≤ Compiler.Constants.evmModulus →
      yulLogDataWords (applyWrites mem (abiBlockWrites base words)) base
          (32 * words.length) = words := by
  intro words
  induction words with
  | nil => intro base mem _; simp [yulLogDataWords]
  | cons word rest ih =>
      intro base mem hfit
      have hfit' : base + 32 + 32 * rest.length ≤ Compiler.Constants.evmModulus := by
        simp only [List.length_cons] at hfit
        omega
      have hcount : 32 * (word :: rest).length / 32 = rest.length + 1 := by
        simp only [List.length_cons]
        omega
      -- memory after the head write, which the tail block extends
      set shadowed : Nat → Nat :=
        fun x => if x = base % Compiler.Constants.evmModulus then word else mem x with hshadow
      have hsplit :
          applyWrites mem (abiBlockWrites base (word :: rest)) =
            applyWrites shadowed (abiBlockWrites (base + 32) rest) := rfl
      have hhead := applyWrites_abiBlockWrites_head word rest base mem hfit'
      have htail := ih (base + 32) shadowed hfit'
      rw [yulLogDataWords, hcount, List.range_succ_eq_map]
      simp only [List.map_cons, List.map_map, Nat.zero_mul, Nat.add_zero, hhead,
        List.cons.injEq, true_and]
      rw [yulLogDataWords,
        show 32 * rest.length / 32 = rest.length from by omega] at htail
      refine Eq.trans ?_ htail
      apply List.map_congr_left
      intro i _
      show applyWrites mem (abiBlockWrites base (word :: rest))
          ((base + (i + 1) * 32) % Compiler.Constants.evmModulus) =
        applyWrites shadowed (abiBlockWrites (base + 32) rest)
          ((base + 32 + i * 32) % Compiler.Constants.evmModulus)
      rw [hsplit, show base + (i + 1) * 32 = base + 32 + i * 32 from by omega]

/-- Pointwise form: the word at ABI slot `index` of the block. -/
theorem applyWrites_abiBlockWrites_getElem
    (base : Nat) (words : List Nat) (mem : Nat → Nat) (index : Nat)
    (hfit : base + 32 * words.length ≤ Compiler.Constants.evmModulus)
    (hindex : index < words.length) :
    applyWrites mem (abiBlockWrites base words)
        ((base + index * 32) % Compiler.Constants.evmModulus) = words[index] := by
  have hread := yulLogDataWords_abiBlockWrites words base mem hfit
  have hcount : 32 * words.length / 32 = words.length := by omega
  have := congrArg (fun ws => ws[index]?) hread
  simpa [yulLogDataWords, hcount, List.getElem?_map, List.getElem?_range, hindex,
    List.getElem?_eq_getElem] using this

/-! ## The slice-1 and slice-2 encoders in memory -/

@[simp] theorem abiEncodeScalarHeads_length (args : List (ParamType × Nat)) :
    (abiEncodeScalarHeads args).length = args.length := by
  simp [abiEncodeScalarHeads]

/-- **Slice-1 composition.**  Writing the scalar ABI heads with `mstore` and
reading the block back yields exactly `abiEncodeScalarHeads`: the memory image
of a static argument block is the ABI head sequence, one word per argument. -/
theorem abiEncodeScalarHeads_memory_layout
    (base : Nat) (args : List (ParamType × Nat)) (mem : Nat → Nat)
    (hfit : base + 32 * args.length ≤ Compiler.Constants.evmModulus) :
    yulLogDataWords
        (applyWrites mem (abiBlockWrites base (abiEncodeScalarHeads args)))
        base (32 * args.length) = abiEncodeScalarHeads args := by
  have hlen : (abiEncodeScalarHeads args).length = args.length :=
    abiEncodeScalarHeads_length args
  have := yulLogDataWords_abiBlockWrites (abiEncodeScalarHeads args) base mem
    (by rw [hlen]; exact hfit)
  rwa [hlen] at this

/-- The `index`-th word of a static block is that argument's ABI head. -/
theorem abiEncodeScalarHeads_memory_head
    (base : Nat) (args : List (ParamType × Nat)) (mem : Nat → Nat) (index : Nat)
    (hfit : base + 32 * args.length ≤ Compiler.Constants.evmModulus)
    (hindex : index < args.length) :
    applyWrites mem (abiBlockWrites base (abiEncodeScalarHeads args))
        ((base + index * 32) % Compiler.Constants.evmModulus) =
      abiEncodeScalarHead (args[index]).1 (args[index]).2 := by
  have hlen : (abiEncodeScalarHeads args).length = args.length :=
    abiEncodeScalarHeads_length args
  have := applyWrites_abiBlockWrites_getElem base (abiEncodeScalarHeads args) mem index
    (by rw [hlen]; exact hfit) (by rw [hlen]; exact hindex)
  simpa [abiEncodeScalarHeads, List.getElem_map] using this

/-- **Slice-2 composition.**  The full dynamic argument block — one head word
per argument followed by the tails in argument order — is exactly what a
32-byte-stride `mstore` block leaves in memory. -/
theorem abiEncodeArgs_memory_layout
    (base : Nat) (args : List AbiArg) (mem : Nat → Nat)
    (hfit : base + 32 * (abiEncodeArgs args).length ≤ Compiler.Constants.evmModulus) :
    yulLogDataWords
        (applyWrites mem (abiBlockWrites base (abiEncodeArgs args)))
        base (32 * (abiEncodeArgs args).length) = abiEncodeArgs args :=
  yulLogDataWords_abiBlockWrites (abiEncodeArgs args) base mem hfit

/-- The dynamic block's head area is `32 * args.length` bytes, and the words
in it are the ABI heads. -/
theorem abiEncodeArgs_memory_head
    (base : Nat) (args : List AbiArg) (mem : Nat → Nat) (index : Nat)
    (hfit : base + 32 * (abiEncodeArgs args).length ≤ Compiler.Constants.evmModulus)
    (hindex : index < args.length) :
    applyWrites mem (abiBlockWrites base (abiEncodeArgs args))
        ((base + index * 32) % Compiler.Constants.evmModulus) =
      (abiEncodeArgHeads args (32 * args.length))[index]'
        (by simpa using hindex) := by
  have hheads : (abiEncodeArgHeads args (32 * args.length)).length = args.length := by
    simp
  have hindex' : index < (abiEncodeArgs args).length := by
    simp only [abiEncodeArgs, List.length_append, hheads]
    omega
  have := applyWrites_abiBlockWrites_getElem base (abiEncodeArgs args) mem index hfit hindex'
  rw [this]
  simp only [abiEncodeArgs]
  rw [List.getElem_append_left (by rw [hheads]; exact hindex)]

/-- **ABI dynamic offset, in memory.**  The memory word at the head slot of a
dynamic argument is the block-relative byte offset `abiTailOffset` of that
argument's tail. -/
theorem abiEncodeArgs_memory_dynamic_offset_points_at_tail
    (base : Nat) (pre : List AbiArg) (arg : AbiArg) (suffix : List AbiArg)
    (mem : Nat → Nat) (hdynamic : arg.isDynamic = true)
    (hfit : base + 32 * (abiEncodeArgs (pre ++ arg :: suffix)).length ≤
      Compiler.Constants.evmModulus) :
    applyWrites mem (abiBlockWrites base (abiEncodeArgs (pre ++ arg :: suffix)))
        ((base + pre.length * 32) % Compiler.Constants.evmModulus) =
      abiTailOffset (pre ++ arg :: suffix) pre.length := by
  have hindex : pre.length < (pre ++ arg :: suffix).length := by simp
  have hhead := abiEncodeArgs_memory_head base (pre ++ arg :: suffix) mem pre.length
    hfit hindex
  rw [hhead]
  have hoffset := abiEncodeArgHeads_dynamic_offset pre arg suffix hdynamic
  have hlen : pre.length <
      (abiEncodeArgHeads (pre ++ arg :: suffix)
        (32 * (pre ++ arg :: suffix).length)).length := by
    simp
  rw [List.getElem?_eq_getElem hlen] at hoffset
  exact Option.some.inj hoffset

end Compiler.Proofs.AbiMemoryLayout

/-! ## Calldatacopy memory readback (#2084)

`dynamicCopyData` (in `Verity.Core.Model.ECM`) materializes dynamic event
tail data with a `calldatacopy` from the transaction's calldata buffer.

**Floor readback** (`yulLogDataWords_calldatacopyMemory`): reading the
`⌊size/32⌋` fully-written words from `dst` returns exactly the calldata
words in order.  This covers the aligned-size case but says nothing about the
final partial word when `size` is not a multiple of 32.

**Ceiling readback** (`yulLogDataWords_calldatacopyMemoryPadded`): the full
byte-granular model `calldatacopyMemoryPadded` extends the base
`calldatacopyMemory` with one ceiling word whose high `size % 32` bytes carry
the copied calldata prefix and whose remaining bytes are zeroed.  Reading the
`⌈size/32⌉` words back returns `calldatacopyWord` for each slot — the full
calldata word for interior slots and the masked/zero-padded word for the
ceiling slot.  This is the form the concrete `bytes`/`string` emit lane
requires, since `compileEmit` passes the raw byte length to `calldatacopy`
but the LOG reads a ceiling-padded ABI region. -/

namespace Compiler.Proofs.CalldataMemoryLayout

open Compiler.Proofs.YulGeneration
open Compiler.Proofs.IRGeneration

/-- **Floor readback of a calldatacopy block.**  Reading `size / 32` consecutive
words back from `dst` — after `calldatacopy(dst, src, size)` — returns exactly
the calldata words from `src, src + 32, …, src + (size/32 - 1) * 32`, provided
the destination block does not wrap the 256-bit address space.

See `yulLogDataWords_calldatacopyMemoryPadded` for the ceiling-word extension
that also covers the partial final word when `size` is not a multiple of 32. -/
theorem yulLogDataWords_calldatacopyMemory
    (selector : Nat) (calldata : List Nat) (dst src size : Nat) (mem : Nat → Nat)
    (hfit : dst + 32 * (size / 32) ≤ Compiler.Constants.evmModulus) :
    yulLogDataWords (calldatacopyMemory selector calldata dst src size mem) dst
        (32 * (size / 32)) =
      (List.range (size / 32)).map (fun i =>
        calldataloadWord selector calldata (src + i * 32)) := by
  simp only [yulLogDataWords, show 32 * (size / 32) / 32 = size / 32 from by omega]
  apply List.map_congr_left
  intro i hi
  rw [List.mem_range] at hi
  have hlt : dst + i * 32 < Compiler.Constants.evmModulus := by omega
  rw [Nat.mod_eq_of_lt hlt,
    calldatacopyMemory_at_index selector calldata dst src size mem i hi]

/-- Pointwise form: the word at ABI slot `index` of the calldatacopy block. -/
theorem calldatacopyMemory_getWord
    (selector : Nat) (calldata : List Nat) (dst src size : Nat) (mem : Nat → Nat)
    (index : Nat)
    (hfit : dst + 32 * (size / 32) ≤ Compiler.Constants.evmModulus)
    (hindex : index < size / 32) :
    calldatacopyMemory selector calldata dst src size mem
        ((dst + index * 32) % Compiler.Constants.evmModulus) =
      calldataloadWord selector calldata (src + index * 32) := by
  have hlt : dst + index * 32 < Compiler.Constants.evmModulus := by omega
  rw [Nat.mod_eq_of_lt hlt,
    calldatacopyMemory_at_index selector calldata dst src size mem index hindex]

/-! ### Ceiling readback -/

/-- **Ceiling readback of a calldatacopy block.**  Reading `⌈size/32⌉`
consecutive words back from `dst` — using the byte-granular model
`calldatacopyMemoryPadded` — returns `calldatacopyWord` at each slot: the
full calldata word for complete interior slots and the masked/zero-padded
word for the final partial slot when `size % 32 ≠ 0`.  This composes with the
concrete `bytes`/`string` emit lane where LOG reads a ceiling-padded region. -/
theorem yulLogDataWords_calldatacopyMemoryPadded
    (selector : Nat) (calldata : List Nat) (dst src size : Nat) (mem : Nat → Nat)
    (hfit : dst + 32 * ((size + 31) / 32) ≤ Compiler.Constants.evmModulus) :
    yulLogDataWords (calldatacopyMemoryPadded selector calldata dst src size mem) dst
        (32 * ((size + 31) / 32)) =
      (List.range ((size + 31) / 32)).map (fun i =>
        calldatacopyWord selector calldata src size i) := by
  simp only [yulLogDataWords,
    show 32 * ((size + 31) / 32) / 32 = (size + 31) / 32 from by omega]
  apply List.map_congr_left
  intro i hi
  rw [List.mem_range] at hi
  have hlt : dst + i * 32 < Compiler.Constants.evmModulus := by omega
  rw [Nat.mod_eq_of_lt hlt]
  simp only [calldatacopyWord]
  split
  · next hfull =>
    exact calldatacopyMemoryPadded_at_index selector calldata dst src size mem i hfull
  · next hceil =>
    have hrem : size % 32 ≠ 0 := by omega
    have heq : i = size / 32 := by omega
    rw [heq]
    exact calldatacopyMemoryPadded_at_ceil selector calldata dst src size mem hrem

/-- Pointwise ceiling form: the word at ABI slot `index` of the
ceiling-padded calldatacopy block. -/
theorem calldatacopyMemoryPadded_getWord
    (selector : Nat) (calldata : List Nat) (dst src size : Nat) (mem : Nat → Nat)
    (index : Nat)
    (hfit : dst + 32 * ((size + 31) / 32) ≤ Compiler.Constants.evmModulus)
    (hindex : index < (size + 31) / 32) :
    calldatacopyMemoryPadded selector calldata dst src size mem
        ((dst + index * 32) % Compiler.Constants.evmModulus) =
      calldatacopyWord selector calldata src size index := by
  have hlt : dst + index * 32 < Compiler.Constants.evmModulus := by omega
  rw [Nat.mod_eq_of_lt hlt]
  simp only [calldatacopyWord]
  split
  · next hfull =>
    exact calldatacopyMemoryPadded_at_index selector calldata dst src size mem index hfull
  · next hceil =>
    have hrem : size % 32 ≠ 0 := by omega
    have heq : index = size / 32 := by omega
    rw [heq]
    exact calldatacopyMemoryPadded_at_ceil selector calldata dst src size mem hrem

/-! ### Ceiling-word regression checks

Executable checks exercising the partial-word cases flagged in the Codex P1
review (PR #2395 `discussion_r3830312802`):
* a 1-byte value (`size = 1`) produces one ceiling word with 1 high byte kept
* a 33-byte value (`size = 33`) produces two words where the second is
  ceiling-masked
These run during `lake build` and fail the build if the mask is wrong. -/

private def regressionCalldata : List Nat := [Compiler.Constants.evmModulus - 1,
  Compiler.Constants.evmModulus - 1]

/-- 1-byte calldatacopy: ceiling word keeps only the topmost byte. -/
theorem ceilWord_regression_1byte :
    calldatacopyWord 0 regressionCalldata 4 1 0 =
      calldataloadWord 0 regressionCalldata 4 /
        2 ^ (8 * (32 - 1)) * 2 ^ (8 * (32 - 1)) := by
  simp [calldatacopyWord]

/-- 33-byte calldatacopy: floor word is unchanged; ceiling word is masked. -/
theorem ceilWord_regression_33byte_floor :
    calldatacopyWord 0 regressionCalldata 4 33 0 =
      calldataloadWord 0 regressionCalldata 4 := by
  simp [calldatacopyWord]

theorem ceilWord_regression_33byte_ceil :
    calldatacopyWord 0 regressionCalldata 4 33 1 =
      calldataloadWord 0 regressionCalldata 36 /
        2 ^ (8 * 31) * 2 ^ (8 * 31) := by
  simp [calldatacopyWord]

/-- Ceiling readback for 33 bytes yields exactly two words. -/
theorem ceilWord_regression_33byte_count :
    (33 + 31) / 32 = 2 := by omega

/-- Aligned size: ceiling count = floor count. -/
theorem ceilWord_regression_aligned :
    (64 + 31) / 32 = 64 / 32 := by omega

end Compiler.Proofs.CalldataMemoryLayout
