"""Exact scalar storage controls and located near-miss rejections."""
import argparse
from pathlib import Path
import re
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--only', default=None)
    args = parser.parse_args()
    root = Path.cwd()
    output = Path(tempfile.mkdtemp(prefix='storage-rejections-', dir=root / '.lake'))
    cases = [
        ('yul-result-shadowed-target', 'function h(uint256 n) internal pure returns(uint256 result) { result = 7; if(n == 0) { uint256 result = n; assembly { result := xor(n,n) } } return result; }', 'return h(x);', 'uint256', 'not the return declaration result'),
        ('yul-result-shadowed-else-target', 'function h(uint256 n) internal pure returns(uint256 result) { result = 7; if(n == 0) { result = 1; } else { uint256 result = n; assembly { result := xor(n,n) } } return result; }', 'return h(x);', 'uint256', 'not the return declaration result'),
        ('yul-result-shadowed-branch-solidity', 'function h(uint256 n) internal pure returns(uint256 result) { result = 7; if(n == 0) { uint256 result = n; result = result + 1; } assembly { result := add(result, 1) } }', 'return h(x);', 'uint256', None),
        ('yul-result-shadowed-bytes-read', 'function h(uint256 n) internal pure returns(uint256 result) { if(n == 0) { bytes memory n = abi.encode(uint256(1)); assembly { result := xor(n,n) } } }', 'return h(x);', 'uint256', 'unbound Yul identifier n'),
        ('yul-result-shadowed-snapshot-read', 'mapping(uint256 => uint16[7]) a; function h(uint256 n) internal view returns(uint256 result) { if(n == 0) { uint16[7] memory n = a[1]; assembly { result := xor(n,n) } } }', 'return h(x);', 'uint256', 'unbound Yul identifier n'),
        ('yul-numeric-decimal', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { r := xor(n, 31) } }', 'return h(x);', 'uint256', None),
        ('yul-numeric-hex', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { r := xor(n, 0x20) } }', 'return h(x);', 'uint256', None),
        ('yul-numeric-word', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { r := 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff } }', 'return h(x);', 'uint256', None),
        ('yul-numeric-add', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { r := add(n, 1) } }', 'return h(x);', 'uint256', None),
        ('yul-numeric-string', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { r := "hello" } }', 'return h(x);', 'uint256', 'only numeric Yul literals are supported'),
        ('yul-numeric-mload', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { r := mload(0) } }', 'return h(x);', 'uint256', 'unsupported Yul builtin mload'),
        ('yul-numeric-create2', 'function h(uint256 n) internal returns(uint256 r) { assembly { r := create2(0, 0, 0, 0) } }', 'return h(x);', 'uint256', 'unsupported Yul builtin create2'),
        ('yul-numeric-block', 'function h(uint256 n) internal pure returns(uint256 r) { assembly { let v := n r := add(v, 1) } }', 'return h(x);', 'uint256', 'only a single Yul assignment is supported'),
        ('named-helper-bare-require', 'function h(uint256 n) internal pure returns(uint256 result) { result = n; require(n != 20); }', 'return h(x);', 'uint256', 'require must resolve to a supported Solidity builtin signature'),
        ('named-helper-default', 'function h(uint256) internal pure returns(uint256 result) { }', 'return h(x);', 'uint256', None),
        ('named-helper-write', 'function h(uint256 n) internal pure returns(uint256 result) { result = n + 1; }', 'return h(x);', 'uint256', None),
        ('named-helper-early', 'function h(uint256 n) internal pure returns(uint256 result) { if(n == 0) return result; result = n; }', 'return h(x);', 'uint256', None),
        ('named-helper-narrow', 'function h(uint256 n) internal pure returns(uint8 result) { assembly { result := xor(n,n) } require(n != 20, "named continuation"); }', 'return h(x);', 'uint256', None),
        ('named-helper-branch', 'function h(uint256 n) internal pure returns(uint256 result) { if(n == 0) { assembly { result := xor(n,n) } } else { result = n; } require(n != 20, "named continuation"); }', 'return h(x);', 'uint256', None),
        ('named-helper-dirty-read', 'function h(uint256 n) internal pure returns(uint8 result) { assembly { result := xor(n,n) } assembly { result := lt(result,n) } }', 'return h(x);', 'uint256', 'Yul reads of narrow named results are unsupported'),
        ('named-helper-reference', 'struct P { uint256 a; } function h(uint256 n) internal pure returns(P memory result) { result = P(n); }', 'h(x); return x;', 'uint256', 'unsupported named helper result type'),
        ('named-helper-tuple', 'function h(uint256 n) internal pure returns(uint256 a,uint256 b) { a = n; b = n; }', 'h(x); return x;', 'uint256', 'only single-value helpers'),
        ('named-helper-modifier', 'modifier m() { _; } function h(uint256 n) internal pure m returns(uint256 result) { result = n; }', 'return h(x);', 'uint256', None),
        ('named-helper-after-return', 'function h(uint256 n) internal pure returns(uint256 result) { return n; result = 0; }', 'return h(x);', 'uint256', 'statement after helper result'),
        ('byte-local-encoded', '', 'bytes memory b = abi.encode(x); return uint256(keccak256(b));', 'uint256', None),
        ('byte-local-alias', '', 'bytes memory b = abi.encode(x); bytes memory c = b; return uint256(keccak256(c));', 'uint256', None),
        ('byte-local-packed', '', 'bytes memory b = abi.encodePacked(hex"01", abi.encode(x)); return uint256(keccak256(b));', 'uint256', None),
        ('byte-local-uninitialized', '', 'bytes memory b; return uint256(keccak256(b));', 'uint256', 'uninitialized reference locals'),
        ('byte-local-reassign', '', 'bytes memory b = abi.encode(x); b = abi.encode(uint256(0)); return uint256(keccak256(b));', 'uint256', 'encoded byte locals are limited to hash and packed encoding operands'),
        ('byte-local-index-write', '', 'bytes memory b = abi.encode(x); b[0] = bytes1(0); return uint256(keccak256(b));', 'uint256', 'encoded byte locals are limited to hash and packed encoding operands'),
        ('byte-local-length', '', 'bytes memory b = abi.encode(x); return b.length;', 'uint256', 'encoded byte locals are limited to hash and packed encoding operands'),
        ('byte-local-new', '', 'bytes memory b = new bytes(x); return uint256(keccak256(b));', 'uint256', 'hash input must be a supported ABI encoding'),
        ('byte-local-helper-reference', 'function h(bytes memory b) internal pure returns (uint256) { return uint256(keccak256(b)); }', 'bytes memory b = abi.encode(x); return h(b);', 'uint256', 'encoded byte locals are limited to hash and packed encoding operands'),
        ('discarded-helper-emit', 'event E(uint256 v); function h(uint256 n) internal returns (uint256) { emit E(n); return n; }', 'h(x); return x;', 'uint256', None),
        ('discarded-helper-emit-anonymous', 'event E(uint256 v) anonymous; function h(uint256 n) internal returns (uint256) { emit E(n); return n; }', 'h(x); return x;', 'uint256', 'anonymous events are unsupported'),
        ('discarded-helper-emit-dynamic', 'event E(string v); function h(uint256 n) internal returns (uint256) { emit E("dynamic"); return n; }', 'h(x); return x;', 'uint256', 'unsupported event parameter type string'),
        ('discarded-helper', 'uint256 v; function h(uint256 n) internal returns (uint256) { v = n; return n; }', 'h(x); return x;', 'uint256', None),
        ('discarded-helper-private', 'function h(uint256 n) private pure returns (uint256) { require(n != 20, "helper"); return n; }', 'h(x); return x;', 'uint256', None),
        ('discarded-helper-void', 'function h(uint256 n) internal { require(n != 20); }', 'h(x); return x;', 'uint256', 'require must resolve to a supported Solidity builtin signature'),
        ('discarded-helper-tuple', 'function h(uint256 n) internal pure returns (uint256,uint256) { return (n,n); }', 'h(x); return x;', 'uint256', 'only single-value helpers'),
        ('discarded-helper-external', 'function h(uint256 n) external pure returns (uint256) { return n; }', 'this.h(x); return x;', 'uint256', 'discarded helper calls require an internal or private'),
        ('discarded-helper-recursive', 'function h(uint256 n) internal returns (uint256) { h(n); return n; }', 'h(x); return x;', 'uint256', 'recursive call'),
        ('discarded-helper-argument-order', 'uint256 v; function h(uint256 n) internal returns (uint256) { v = n; return n; }', 'h(h(x)); return x;', 'uint256', 'stateful helper call arguments'),
        ('fixed-array-read', 'mapping(uint256 => uint16[7]) a;', 'return a[1][x];', 'uint256', None),
        ('fixed-array-write', 'mapping(uint256 => uint16[7]) a;', 'a[1][x] = 7; delete a[1][0]; return a[1][x];', 'uint256', None),
        ('fixed-array-copy', 'mapping(uint256 => uint16[7]) a;', 'uint16[7] memory copy = a[1]; a[1][0] = 7; return copy[x];', 'uint256', None),
        ('fixed-array-two', 'mapping(uint256 => mapping(address => uint24[12])) a;', 'a[1][msg.sender][x] = 7; return a[1][msg.sender][x];', 'uint256', None),
        ('fixed-array-dynamic', 'mapping(uint256 => uint16[]) a;', 'return a[1][x];', 'uint256', 'unsupported mapping value encoding'),
        ('fixed-array-dimension', 'mapping(uint256 => uint16[7][2]) a;', 'return a[1][0][x];', 'uint256', 'exactly one fixed dimension'),
        ('fixed-array-signed', 'mapping(uint256 => int16[7]) a;', 'a[1][x] = 1; return x;', 'uint256', 'unsigned scalar elements'),
        ('fixed-array-bool', 'mapping(uint256 => bool[7]) a;', 'return a[1][x] ? 1 : 0;', 'uint256', 'unsigned scalar elements'),
        ('fixed-array-memory-write', 'mapping(uint256 => uint16[7]) a;', 'uint16[7] memory copy = a[1]; copy[0] = 7; return copy[0];', 'uint256', 'mapping assignment target is not a storage path'),
        ('fixed-array-memory-alias', 'mapping(uint256 => uint16[7]) a;', 'uint16[7] memory copy = a[1]; uint16[7] memory aliasCopy = copy; return aliasCopy[0];', 'uint256', 'initialization requires a mapping storage array'),
        ('fixed-array-key-effect', 'mapping(uint256 => uint256[7]) a;', 'a[x + 1][0] = 7; return x;', 'uint256', None),
        ('fixed-array-index-effect', 'mapping(uint256 => uint256[7]) a;', 'a[1][x + 1] = 7; return x;', 'uint256', None),
        ('fixed-array-rhs-effect', 'mapping(uint256 => uint256[7]) a;', 'a[1][x] = x + 1; return x;', 'uint256', None),
        ('fixed-array-write-stateful-binary', 'mapping(uint256 => uint256[7]) a; uint256 s; function bump() internal returns (uint256) { s = s + 1; return s; }', 'a[1][x] = bump() + bump(); return x;', 'uint256', 'stateful helper operands require explicit evaluation-order support'),
        ('fixed-array-write-dynamic', 'mapping(uint256 => uint256[]) a;', 'a[1][x] = 7; return x;', 'uint256', 'unsupported mapping value encoding'),
        ('fixed-array-compound', 'mapping(uint256 => uint256[7]) a;', 'a[1][x] += 1; return x;', 'uint256', 'only scalar storage assignment and delete'),

        ('helper-effect-write', 'uint256 value; function helper(uint256 n) internal returns (uint256) { value = n; return value; }', 'return helper(x);', 'uint256', None),
        ('helper-effect-delete', 'mapping(uint256 => uint256) value; function helper(uint256 n) internal returns (uint256) { value[1] = n; delete value[1]; return value[1]; }', 'return helper(x);', 'uint256', None),
        ('helper-effect-compound', 'uint256 value; function helper(uint256 n) internal returns (uint256) { value += n; return value; }', 'return helper(x);', 'uint256', None),
        ('helper-effect-increment', 'uint256 value; function helper(uint256 n) internal returns (uint256) { value++; return n; }', 'return helper(x);', 'uint256', 'only scalar storage assignment and delete'),
        ('helper-effect-parameter', 'function helper(uint256 n) internal pure returns (uint256) { n = 0; return n; }', 'return helper(x);', 'uint256', 'only materialized scalar locals are writable'),
        ('helper-effect-root-struct', 'struct Box { uint256 low; } Box box; function helper(uint256 n) internal returns (uint256) { box.low = n; return n; }', 'return helper(x);', 'uint256', 'member assignment requires a mapping struct storage path'),
        ('helper-effect-external', 'function helper(uint256 n) internal returns (uint256) { this.checked(n); return n; }', 'return helper(x);', 'uint256', 'discarded helper calls require an internal or private'),
        ('member-write', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'boxes[1].low = uint8(x); return uint256(boxes[1].low);', 'uint256', None),
        ('member-delete', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'delete boxes[1].low; return uint256(boxes[1].low);', 'uint256', None),
        ('member-key-prelude', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'boxes[x + 1].low = 7; return x;', 'uint256', 'member write key prelude'),
        ('member-compound', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'boxes[1].low += 1; return x;', 'uint256', None),
        ('member-increment', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'boxes[1].low++; return x;', 'uint256', 'only scalar storage assignment and delete'),
        ('member-whole-struct', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'boxes[1] = Box(1, 2); return x;', 'uint256', 'only scalar mapping values are writable'),
        ('member-memory', 'struct Box { uint8 low; uint128 sibling; } mapping(uint256 => Box) private boxes;', 'Box memory box = Box(1, 2); box.low = 7; return x;', 'uint256', 'unsupported call kind'),
        ('member-opaque', 'struct Box { uint8 low; uint256[] values; } mapping(uint256 => Box) private boxes;', 'delete boxes[1].values; return x;', 'uint256', 'member values is opaque'),
        ('member-address', 'struct Box { address owner; } mapping(uint256 => Box) private boxes;', 'boxes[1].owner = address(0); return x;', 'uint256', 'unsupported layout member'),
        ('member-signed', 'struct Box { int128 low; } mapping(uint256 => Box) private boxes;', 'boxes[1].low = 1; return x;', 'uint256', 'unsupported layout member'),
        ('helper-for', 'function helper(uint256 n) internal pure returns (uint256) { uint256 total; for (uint256 i = 0; i < n; i++) { total = total + i; } return total; }', 'return helper(x);', 'uint256', None),
        ('helper-for-return', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i < n; i++) { return i; } return 0; }', 'return helper(x);', 'uint256', 'return inside an inlined helper loop'),
        ('helper-for-conditional-return', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i < n; i++) { if (i == 1) return i; } return 0; }', 'return helper(x);', 'uint256', 'return inside an inlined helper loop'),
        ('helper-for-break', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i < n; i++) { break; } return 0; }', 'return helper(x);', 'uint256', 'unsupported helper loop statement Break'),
        ('helper-for-continue', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i < n; i++) { continue; } return 0; }', 'return helper(x);', 'uint256', 'unsupported helper loop statement Continue'),
        ('helper-for-step', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i < n; i += 2) {} return 0; }', 'return helper(x);', 'uint256', 'increment its counter by one'),
        ('helper-for-inclusive', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i <= n; i++) {} return 0; }', 'return helper(x);', 'uint256', 'condition must be counter < bound'),
        ('helper-for-counter', 'function helper(uint256 n) internal pure returns (uint256) { for (uint256 i = 0; i < n; i++) { i = 2; } return 0; }', 'return helper(x);', 'uint256', 'counter must not be assigned'),
        ('helper-for-bound', 'function helper(uint256 n) internal pure returns (uint256) { uint256 bound = n; for (uint256 i = 0; i < bound; i++) { bound = 0; } return 0; }', 'return helper(x);', 'uint256', 'bound must be a literal'),
        ('helper-for-nested-bound', 'function helper(uint256 n) internal pure returns (uint256) { uint256 bound = n; for (uint256 i = 0; i < bound; i++) { for (uint256 j = 0; j < 1; bound++) {} } return 0; }', 'return helper(x);', 'uint256', 'bound must be a literal'),
        ('for-scalar', '', 'uint256 total; for (uint256 i = 0; i < 3; i++) { total = total + i; } return total;', 'uint256', None),
        ('for-nonzero', '', 'for (uint256 i = 1; i < 3; i++) {} return x;', 'uint256', 'counter must start at 0'),
        ('for-inclusive', '', 'for (uint256 i = 0; i <= 3; i++) {} return x;', 'uint256', 'condition must be counter < bound'),
        ('for-variable-step', '', 'for (uint256 i = 0; i < 3; i += 2) {} return x;', 'uint256', 'increment its counter by one'),
        ('for-counter-write', '', 'for (uint256 i = 0; i < 3; i++) { i = 2; } return x;', 'uint256', 'counter must not be assigned'),
        ('for-bound-write', '', 'uint256 n = x; for (uint256 i = 0; i < n; i++) { n = 0; } return x;', 'uint256', 'bound must be a literal'),
        ('for-nested-bound-step', '', 'uint256 n = x; for (uint256 i = 0; i < n; i++) { for (uint256 j = 0; j < 1; n++) {} } return x;', 'uint256', 'bound must be a literal'),
        ('for-break', '', 'for (uint256 i = 0; i < 3; i++) { break; } return x;', 'uint256', 'unsupported statement Break'),
        ('for-continue', '', 'for (uint256 i = 0; i < 3; i++) { continue; } return x;', 'uint256', 'unsupported statement Continue'),
        ('default-uint', '', 'uint256 zero; return x + zero;', 'uint256', None),
        ('default-narrow', '', 'uint8 zero; return uint256(zero);', 'uint256', None),
        ('default-address', '', 'address zero; return zero;', 'address', None),
        ('default-bool', '', 'bool zero; return zero;', 'bool', None),
        ('default-bytes32', '', 'bytes32 zero; return zero;', 'bytes32', None),
        ('default-signed', '', 'int256 zero; return zero;', 'int256', None),
        ('default-narrow-signed', '', 'int128 zero; return x;', 'uint256', 'unsupported default local type int128'),
        ('default-bytes', '', 'bytes memory zero; return x;', 'uint256', 'uninitialized reference locals'),
        ('default-array', '', 'uint256[] memory zero; return x;', 'uint256', 'uninitialized reference locals'),
        ('modulo-unsigned', '', 'return x % 7;', 'uint256', None),
        ('modulo-narrow', '', 'return uint8(x) % uint8(7);', 'uint256', None),
        ('modulo-signed', '', 'return uint256(int256(x) % int256(7));', 'uint256', 'modulo requires unsigned scalar operands'),
        ('modulo-rational-constant', '', 'return x + (7 % 2);', 'uint256', 'unsupported operand type'),
        ('inline-constant-array', 'uint256 constant A = 3;', 'return [A, 7][x];', 'uint256', None),
        ('inline-constant-array-narrow', 'uint8 constant A = 255; uint8 constant B = 0;', 'return [A, B][x];', 'uint256', None),
        ('inline-array-variable', '', 'return [x, 7][x];', 'uint256', 'inline array elements must be exact natural constants'),
        ('inline-array-guarded-element', '', 'return [uint256(1), 100 / x][x];', 'uint256', 'inline array elements must be exact natural constants'),
        ('inline-array-bool', '', 'return [true, false][x];', 'bool', 'inline constant arrays require unsigned scalar elements'),
        ('inline-array-signed', '', 'return uint256([int256(-1), int256(2)][x]);', 'uint256', 'inline constant arrays require unsigned scalar elements'),
        ('inline-array-escape', '', 'uint256[2] memory a = [uint256(1), 2]; return a[x];', 'uint256', 'inline arrays are outside this slice'),
        ('if-else', '', 'if (x > 1) { return 1; } else { return 2; }', 'uint256', None),
        ('if-early-return', 'uint256 value;', 'if (x == 0) return 0; value = x; return value;', 'uint256', None),
        ('if-helper-return', 'function h(uint256 y) internal pure returns (uint256) { if (y > 1) return 1; require(y == 0, "one"); return 0; }', 'return h(x);', 'uint256', None),
        ('if-bare-return', 'uint256 value;', 'if (x == 0) return; value = x;', '', None),
        ('if-dead-remainder', '', 'if (false) { return x % 2; } return x;', 'uint256', None),
        ('if-dead-rational-remainder', '', 'if (false) { return x % (6 / 3); } return x;', 'uint256', 'unsupported operand type'),
        ('if-after-both-return', 'uint256 value;', 'if (x > 1) { return 1; } else { return 2; } value = x;', 'uint256', 'statement after root return'),
        ('if-helper-missing-return', 'function h(uint256 y) internal pure returns (uint256) { if (y > 1) return 1; }', 'return h(x);', 'uint256', 'does not return on every path'),
        ('if-helper-after-both-return', 'function h(uint256 y) internal pure returns (uint256) { if (y > 1) { return 1; } else { return 2; } require(y > 0, "dead"); }', 'return h(x);', 'uint256', 'statement after helper result'),
        ('if-helper-effect', 'uint256 value; function h(uint256 y) internal returns (uint256) { if (y > 1) { value = y; } return y; }', 'return h(x);', 'uint256', None),
        ('if-helper-effect-compound', 'uint256 value; function h(uint256 y) internal returns (uint256) { if (y > 1) { value += y; } return y; }', 'return h(x);', 'uint256', None),
        ('if-unchecked-branch', '', 'if (x > 1) { unchecked { return x - 2; } } return x;', 'uint256', None),
        ('logical-or', '', 'return x == 0 || 100 / x > 1;', 'bool', None),
        ('logical-and', '', 'return x != 0 && 100 / x > 1;', 'bool', None),
        ('logical-dead-effect', 'uint256 value; function bump() internal returns (bool) { value = 1; return true; }', 'return true || bump();', 'bool', None),
        ('logical-dead-remainder', '', 'return false && x % 2 == 0;', 'bool', None),
        ('logical-dead-rational-remainder', '', 'return false && x % (6 / 3) == 0;', 'bool', 'unsupported operand type'),
        ('logical-external', 'function probe() external pure returns (bool) { return true; }', 'return true || this.probe();', 'bool', 'unresolved builtin identifier'),

        ('effectful-helper', 'uint256 value; function bump() internal returns (uint256) { value = value + 1; return value; }', 'return bump() + bump();', 'uint256', 'stateful helper operands require explicit evaluation-order support'),
        ('helper-argument-effects', 'uint256 value; function bump() internal returns (uint256) { value = value + 1; return value; } function add(uint256 a, uint256 b) internal pure returns (uint256) { return a + b; }', 'return add(bump(), bump());', 'uint256', 'stateful helper call arguments require explicit evaluation-order support'),
        ('bare-return', 'uint256 value;', 'value = x; return;', '', None),
        ('scalar', 'uint256 value;', 'value = x; return value;', 'uint256', None),
        ('packed', 'uint128 low; uint128 high;', 'high = uint128(x); return high;', 'uint128', None),
        ('delete', 'uint256 value;', 'delete value; return value;', 'uint256', None),
        ('void', 'uint256 value;', 'value = x;', '', None),
        ('bool', 'bool value;', 'value = true; return x;', 'uint256', None),
        ('signed', 'int256 value;', 'value = int256(x); return x;', 'uint256', None),
        ('signed-narrow', 'int128 value;', 'delete value; return x;', 'uint256', 'unsupported scalar storage type'),
        ('bytes16', 'bytes16 value;', 'delete value; return x;', 'uint256', 'unsupported scalar storage type'),
        ('array', 'uint256[] value;', 'delete value; return x;', 'uint256', 'unsupported storage encoding'),
        ('mapping-target', 'mapping(uint256 => uint256) value;', 'value[x] = x; return x;', 'uint256', None),
        ('mapping-bool', 'mapping(uint256 => bool) value;', 'value[x] = true; return value[x];', 'bool', None),
        ('mapping-delete', 'mapping(uint256 => uint128) value;', 'value[x] = uint128(x); delete value[x]; return value[x];', 'uint128', None),
        ('mapping-two-keys', 'mapping(address => mapping(bytes32 => uint128)) value;', 'value[msg.sender][bytes32(x)] = uint128(x); return value[msg.sender][bytes32(x)];', 'uint128', None),
        ('mapping-three-keys', 'mapping(uint256 => mapping(uint256 => mapping(uint256 => uint256))) value;', 'return value[x][x][x];', 'uint256', 'unsupported scalar mapping value encoding'),
        ('mapping-signed-value', 'mapping(uint256 => int256) value;', 'return value[x];', 'int256', None),
        ('mapping-narrow-signed-value', 'mapping(uint256 => int128) value;', 'delete value[x]; return x;', 'uint256', 'unsupported scalar mapping value type'),
        ('mapping-bytes16-value', 'mapping(uint256 => bytes16) value;', 'return value[x];', 'bytes16', 'unsupported scalar mapping value type'),
        ('mapping-signed-key', 'mapping(int256 => uint256) value;', 'return value[0];', 'uint256', 'unsupported mapping key'),
        ('mapping-narrow-key', 'mapping(uint128 => uint256) value;', 'return value[uint128(x)];', 'uint256', 'unsupported mapping key'),
        ('mapping-dynamic-value', 'mapping(uint256 => bytes) value;', 'delete value[x]; return x;', 'uint256', 'unsupported mapping value encoding'),
        ('mapping-compound', 'mapping(uint256 => uint256) value;', 'value[x] += x; return value[x];', 'uint256', None),
        ('literal-constant-product', '', 'return x + (2 * 3);', 'uint256', None),
        ('literal-constant-product-units', '', 'return x + (100 * 365 days);', 'uint256', None),
        ('literal-fractional-product', '', 'return x + (.5 * 2);', 'uint256', 'fractional numeric literal'),
        ('literal-rational-division', '', 'return x + (6 / 3);', 'uint256', 'unsupported operand type'),
        ('literal-product-oversized-intermediate', '', 'return x + (57896044618658097711785492504343953926634992332820282019728792003956564819968 * 2 / 2);', 'uint256', 'unsupported integer constant product'),
        ('literal-leading-dot', '', 'return .5 hours;', 'uint256', None),
        ('literal-separators', '', 'return 1_000 + 0x2_0;', 'uint256', None),
        ('literal-fractional-result', '', 'return x + (.5 / .5);', 'uint256', 'fractional numeric literal'),
        ('literal-bool-constant', 'bool constant ENABLED = true;', 'return ENABLED;', 'bool', None),
        ('literal-narrow-constant', 'uint8 constant LIMIT = 255;', 'return x + LIMIT;', 'uint256', None),
        ('literal-bytes-constant', 'bytes32 constant BAD = bytes32(uint256(1));', 'return uint256(BAD);', 'uint256', 'unsupported numeric constant type bytes32'),
        ('literal-address-constant', 'address constant BAD = address(1);', 'return uint256(uint160(BAD));', 'uint256', 'unsupported numeric constant type address'),
        ('literal-signed-constant', 'int256 constant BAD = -1;', 'return uint256(BAD);', 'uint256', 'unsupported numeric constant type int256'),
        ('literal-named-rational', 'uint256 constant STEP = (1 days / 7) * 7;', 'return x + STEP;', 'uint256', 'unsupported operand type'),
        ('literal-constant-fraction', '', 'return x + (1 days / 7) * 7;', 'uint256', 'unsupported operand type'),
        ('literal-oversized-intermediate', '', 'return x + (2**256 / 2);', 'uint256', 'unsupported operand type'),
        ('literal-denomination', '', 'return 1 ether;', 'uint256', None),
        ('literal-string', '', 'return bytes32("123");', 'bytes32', 'unsupported non-numeric literal'),
        ('struct-target', 'struct Pair { uint128 a; uint128 b; } Pair value;', 'value.a = uint128(x); return x;', 'uint256', 'member assignment requires a mapping struct storage path'),
        ('compound', 'uint256 value;', 'value += x; return value;', 'uint256', None),
        ('increment', 'uint256 value;', 'value++; return value;', 'uint256', 'only scalar storage assignment'),
        ('local', '', 'uint256 value = 0; value = x; return value;', 'uint256', None),
        ('local-delete', '', 'uint256 value = x; delete value; return value;', 'uint256', None),
        ('local-compound', '', 'uint256 value = 0; value += x; return value;', 'uint256', None),
        ('local-increment', '', 'uint256 value = 0; value++; return value;', 'uint256', 'only scalar storage assignment'),
        ('parameter-write', '', 'x = 0; return x;', 'uint256', 'only materialized scalar locals are writable'),
        ('helper-parameter-write', 'function h(uint256 y) internal pure returns (uint256) { y = 0; return y; }', 'uint256 local = x; return h(local);', 'uint256', 'only declaration-bound scalar locals are writable'),
        ('local-array-write', '', 'uint256[2] memory a; a[0] = x; return x;', 'uint256', 'uninitialized reference locals'),
        ('named-return', 'uint256 value;', 'value = x;', 'uint256 result', None),
    ]
    for name, fields, body, returns, expected in cases:
        if args.only and args.only not in name:
            continue
        directory = output / name
        directory.mkdir()
        result_clause = f'returns ({returns})' if returns else ''
        (directory / 'Fixture.sol').write_text(f'''pragma solidity 0.8.34;
contract C {{
 {fields}
 function checked(uint256 x) external {result_clause} {{
  {body}
 }}
}}
''')
        driver = directory / 'Check.lean'
        driver.write_text(f'''import Compiler.SolidityImport.Import
solidity_import tested from "{directory}" entry "Fixture.sol"
  using {{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }}
  contract C
  function checked(uint256)
''')
        artifact = directory / 'Check.olean'
        result = subprocess.run(['lake', 'env', 'lean', str(driver), '-o', str(artifact)],
                                cwd=root, text=True, capture_output=True, timeout=120)
        text = result.stdout + result.stderr
        (directory / 'check.log').write_text(text)
        if expected is None:
            if result.returncode or not artifact.exists():
                raise RuntimeError(f'{name}: positive control failed\n{text}')
        elif (result.returncode == 0 or artifact.exists() or expected not in text or
              not re.search(r'Fixture\.sol:\d+:\d+:', text)):
            raise RuntimeError(f'{name}: expected located rejection {expected!r}\n{text}')
        print(f'pass storage-{name}', flush=True)
    solc_0810_cases = [
        ('solc-0810-single-quote-import',
         "pragma solidity 0.8.10;\nimport './Dep.sol';\ncontract C { function checked(uint256 x) external pure returns (uint256) { return Dep.addOne(x); } }\n",
         "pragma solidity 0.8.10;\nlibrary Dep { function addOne(uint256 x) internal pure returns (uint256) { return x + 1; } }\n",
         '{ solc := "0.8.10+commit.fc410830", evmVersion := "london", viaIR := false, optimizerRuns := some 1, bytecodeHash := "none" }',
         None),
        ('solc-0810-osaka-rejected',
         "pragma solidity 0.8.10;\ncontract C { function checked(uint256 x) external pure returns (uint256) { return x; } }\n",
         None,
         '{ solc := "0.8.10+commit.fc410830", evmVersion := "osaka", viaIR := false, optimizerRuns := some 1, bytecodeHash := "none" }',
         'evmVersion osaka is not supported for solc 0.8.10+commit.fc410830'),
        ('solc-0810-viair-rejected',
         "pragma solidity 0.8.10;\ncontract C { function checked(uint256 x) external pure returns (uint256) { return x; } }\n",
         None,
         '{ solc := "0.8.10+commit.fc410830", evmVersion := "london", viaIR := true, optimizerRuns := some 1, bytecodeHash := "none" }',
         'viaIR is not supported for solc 0.8.10+commit.fc410830'),
        ('solc-0810-unknown-release-rejected',
         "pragma solidity 0.8.10;\ncontract C { function checked(uint256 x) external pure returns (uint256) { return x; } }\n",
         None,
         '{ solc := "0.8.10+commit.deadbeef", evmVersion := "london", viaIR := false, optimizerRuns := some 1, bytecodeHash := "none" }',
         'this importer is pinned to solc 0.8.34+commit.80d5c536 or 0.8.10+commit.fc410830, not 0.8.10+commit.deadbeef'),
        ('inheritance-root-function',
         "pragma solidity 0.8.10;\nimport './Dep.sol';\ncontract C is Base { }\n",
         "pragma solidity 0.8.10;\nabstract contract Base { uint256 internal s; function checked(uint256 x) external returns (uint256) { s = x + 1; return s; } }\n",
         '{ solc := "0.8.10+commit.fc410830", evmVersion := "london", viaIR := false, optimizerRuns := some 1, bytecodeHash := "none" }',
         None),
        ('inheritance-diamond-super-and-virtual',
         "pragma solidity 0.8.34;\nimport './Dep.sol';\ncontract C is Left, Right {\n  function bonus(uint256 x) internal pure override returns (uint256) { return x * 2; }\n  function step(uint256 x) internal override(Left, Right) returns (uint256) { uint256 a = super.step(x); uint256 b = Root.step(x); return a + b + viaBonus(x); }\n  function checked(uint256 x) external returns (uint256) { return step(x); }\n}\n",
         "pragma solidity 0.8.34;\nabstract contract Root {\n  uint256 internal v;\n  function bonus(uint256 x) internal pure virtual returns (uint256) { return x; }\n  function viaBonus(uint256 x) internal pure returns (uint256) { return bonus(x); }\n  function step(uint256 x) internal virtual returns (uint256) { v = x + 1; return v; }\n}\nabstract contract Left is Root {\n  uint256[4] private __gap;\n  function step(uint256 x) internal virtual override returns (uint256) { uint256 p = super.step(x); return p + 10; }\n}\nabstract contract Right is Root {\n  uint256[4] private __gap;\n  function step(uint256 x) internal virtual override returns (uint256) { uint256 p = super.step(x); return p + 100; }\n}\n",
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('inheritance-stateful-super-binary-rejected',
         "pragma solidity 0.8.34;\nabstract contract Base { uint256 internal v; function step(uint256 x) internal virtual returns (uint256) { v = x + 1; return v; } }\ncontract C is Base { function checked(uint256 x) external returns (uint256) { return super.step(x) + 1; } }\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:3:86: BinaryOperation: [solidity-import:unsupported] stateful helper operands require explicit evaluation-order support'),
        ('inheritance-interface-unimplemented-rejected',
         "pragma solidity 0.8.34;\ninterface IBase { function checked(uint256 x) external view returns (uint256); }\nabstract contract C is IBase { }\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'function is not implemented'),
        ('inheritance-external-contract-call-rejected',
         "pragma solidity 0.8.34;\ninterface IPeer { function ping(uint256 x) external view returns (uint256); }\ncontract C { function checked(uint256 x) external view returns (uint256) { return IPeer(msg.sender).ping(x); } }\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:3:83: MemberAccess: [solidity-import:unsupported] external contract calls are outside this slice'),
        ('inheritance-duplicate-private-storage-rejected',
         "pragma solidity 0.8.34;\nabstract contract Base { uint256 private dup; }\ncontract C is Base { uint256 private dup; function checked(uint256 x) external returns (uint256) { dup = x; return dup; } }\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:3:100: Identifier: [solidity-import:unsupported] shadowed storage declaration dup is outside this slice'),
        ('inheritance-overloaded-function-rejected',
         "pragma solidity 0.8.34;\nabstract contract Base { function step(address a) internal pure returns (uint256) { return uint256(uint160(a)); } }\ncontract C is Base { function step(uint256 x) internal pure returns (uint256) { return x + 1; } function checked(uint256 x) external pure returns (uint256) { return step(x); } }\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:3:166: Identifier: [solidity-import:unsupported] ambiguous declaration'),
        ('void-helper-nested-return-and-revert-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  error GuardErr(uint256 x);\n  bool private flag;\n  uint256 private v;\n  function _hook(uint256) internal pure returns (uint256) {}\n  function _step(uint256 x) internal {\n    if (x == 9) revert GuardErr(x);\n    if (flag) { if (!flag) { v = 1; return; } }\n    flag = !flag;\n    v = v + x + _hook(x);\n  }\n  function checked(uint256 x) external returns (uint256 out) {\n    _step(x);\n    out = v + (flag ? 1 : 0);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('void-root-bare-return-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function checked(uint256 x) external {\n    if (x == 7) return;\n    v = x;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('void-helper-dead-statement-after-return-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function _step(uint256 x) internal { return; v = x; }\n  function checked(uint256 x) external returns (uint256) { _step(x); return v; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:48: ExpressionStatement: [solidity-import:unsupported] statement after void helper return'),
        ('void-helper-dead-statement-after-revert-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  error GuardErr(uint256 x);\n  uint256 private v;\n  function _step(uint256 x) internal { revert GuardErr(x); v = x; }\n  function checked(uint256 x) external returns (uint256) { _step(x); return v; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:5:60: ExpressionStatement: [solidity-import:unsupported] statement after void helper revert'),
        ('void-helper-loop-return-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function _step(uint256 n) internal { for (uint256 i = 0; i < n; i++) { return; } }\n  function checked(uint256 x) external returns (uint256) { _step(x); return v; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:74: Return: [solidity-import:unsupported] return inside an inlined helper loop is unsupported'),
        ('unnamed-root-bare-return-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) { if (x == 0) return; return x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'solc:'),
        ('unnamed-nonempty-root-fallthrough-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function checked(uint256 x) external returns (uint256) { v = x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:3: FunctionDefinition: [solidity-import:unsupported] an explicit root return is required'),
        ('modifier-unchecked-compound-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  uint64 private w;\n  modifier guard(uint256 x) { require(x != 9, \"guard\"); v += 1; _; }\n  function syncPub(uint256 x) public { v += x + (10 ** 2); }\n  function checked(uint256 x) external guard(x) returns (uint256) {\n    syncPub(x);\n    unchecked { w -= uint64(x + 1); }\n    uint256 y = (v = x + 3) + 2;\n    return y + uint256(w);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('modifier-return-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  modifier m() { _; return; }\n  function checked(uint256 x) external m returns (uint256) { return x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:3: ModifierDefinition: [solidity-import:unsupported] return inside a modifier is outside this slice'),
        ('modifier-branch-placeholder-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  modifier m(uint256 x) { if (x > 0) { _; } _; }\n  function checked(uint256 x) external m(x) pure returns (uint256) { return x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:3:3: ModifierDefinition: [solidity-import:unsupported] only a single top-level _; placeholder is supported in modifiers'),
        ('modifier-virtual-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  modifier m() virtual { _; }\n  function checked(uint256 x) external m pure returns (uint256) { return x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:3:3: ModifierDefinition: [solidity-import:unsupported] virtual modifiers are outside this slice'),
        ('compound-mul-assign-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function checked(uint256 x) external returns (uint256) { v *= x; return v; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:60: Assignment: [solidity-import:unsupported] only scalar storage assignment and delete are supported'),
        ('compound-assignment-expr-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function checked(uint256 x) external returns (uint256) { return (v += x) + 1; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:68: Assignment: [solidity-import:unsupported] compound assignment expressions are outside this slice'),
        ('assignment-expr-sibling-order-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function checked(uint256 x) external returns (uint256) { return (v = x) + v; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:67: BinaryOperation: [solidity-import:unsupported] assignment operand with non-atomic sibling requires explicit evaluation-order support'),
        ('assignment-expr-multi-arg-call-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function add(uint256 a, uint256 b) internal pure returns (uint256) { return a + b; }\n  function checked(uint256 x) external returns (uint256) { return add(v = x, 1); }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:5:71: Assignment: [solidity-import:unsupported] assignment expression in multi-argument call requires explicit evaluation-order support'),
        ('assignment-expr-mapping-target-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  mapping(uint256 => uint256) private m;\n  function checked(uint256 x) external returns (uint256) { return (m[0] = x) + 1; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Fixture.sol:4:68: IndexAccess: [solidity-import:unsupported] assignment expressions currently require a scalar local or storage identifier'),
        ('tuple-helper-param-compound-and-narrow-emit-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  event Init(uint8 version);\n  uint256 private s;\n  function _pair(uint256 y) internal pure returns (uint256 a, uint256 b) {\n    y += 2;\n    a = y;\n    b = y + 3;\n  }\n  function checked(uint256 x) external returns (uint256) {\n    emit Init(type(uint8).max);\n    x += 1;\n    (uint256 a, uint256 b) = _pair(x);\n    (s, a) = _pair(b);\n    return s + a;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('tuple-destructure-non-call-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    (uint256 a, uint256 b) = (x, x + 1);\n    return a + b;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'TupleExpression: [solidity-import:unsupported] tuple destructuring requires a multi-return helper call'),
        ('tuple-assignment-duplicate-target-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function _pair(uint256 y) internal pure returns (uint256, uint256) { return (y, y + 1); }\n  function checked(uint256 x) external pure returns (uint256) {\n    uint256 a = 0;\n    (a, a) = _pair(x);\n    return a;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Identifier: [solidity-import:unsupported] duplicate or invalid target in tuple assignment'),
        ('tuple-assignment-mapping-target-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  mapping(uint256 => uint256) private m;\n  function _pair(uint256 y) internal pure returns (uint256, uint256) { return (y, y + 1); }\n  function checked(uint256 x) external returns (uint256) {\n    (m[0], m[1]) = _pair(x);\n    return m[0];\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'IndexAccess: [solidity-import:unsupported] tuple assignment target must be a scalar local or storage identifier'),
        ('multi-helper-missing-return-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function _pair(uint256 y) internal pure returns (uint256, uint256) { if (y > 0) return (y, y); }\n  function checked(uint256 x) external pure returns (uint256) {\n    (uint256 a, uint256 b) = _pair(x);\n    return a + b;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionDefinition: [solidity-import:unsupported] inlined multi-return helper does not return on every path'),
        ('multi-helper-stateful-return-tuple-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function _bump() internal returns (uint256) { v += 1; return v; }\n  function _pair(uint256 y) internal returns (uint256, uint256) { return (_bump(), y); }\n  function checked(uint256 x) external returns (uint256) {\n    (uint256 a, uint256 b) = _pair(x);\n    return a + b;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCall: [solidity-import:unsupported] stateful or assignment expression in multi-return tuple requires explicit evaluation-order support'),
        ('int256-and-contract-types-accepted',
         "pragma solidity 0.8.34;\ninterface IPeer { function ping(uint256 x) external view returns (uint256); }\ncontract C {\n  IPeer private peer;\n  mapping(uint256 => IPeer) private peers;\n  int256 private acc;\n  mapping(uint256 => int256) private deltas;\n  function _pick(IPeer p, int256 d) internal pure returns (IPeer, int256) {\n    d += 3;\n    return (p, -d);\n  }\n  function checked(uint256 x) external returns (uint256) {\n    (IPeer p, int256 d) = _pick(IPeer(msg.sender), -int256(x % 10));\n    peer = p;\n    peers[0] = peer;\n    deltas[0] += d / int256(-2);\n    acc += deltas[0] + (type(int256).max > 0 && type(int256).min < 0 && type(uint256).min == 0 ? int256(1) : int256(0));\n    return uint256(acc) + uint256(uint160(address(peers[0])));\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('int256-narrow-cast-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    return uint256(uint128(int128(int256(x))));\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCall: [solidity-import:unsupported] unsupported cast target int128'),
        ('int256-type-bound-narrow-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    return type(int128).max > 0 ? x : 0;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] unsupported type().max int128'),
        ('function-pointer-identifier-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function _helper(uint256 y) internal pure returns (uint256) { return y; }\n  function checked(uint256 x) external pure returns (uint256) {\n    return _helper == _helper ? x : 0;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Identifier: [solidity-import:unsupported] function pointers are outside this slice'),
        ('fn-ptr-struct-delete-post-modifier-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  struct Order { uint128 amount; uint128 fee; uint256 epoch; }\n  uint256 private lock;\n  mapping(uint256 => Order) private orders;\n  modifier guard() { require(lock == 0, \"locked\"); lock = 1; _; lock = 0; }\n  function _f1(uint256 a) internal pure returns (uint256) { return a + 1; }\n  function _f2(uint256 a) internal pure returns (uint256) { return a + 2; }\n  function checked(uint256 x) external guard returns (uint256 out) {\n    function (uint256) internal pure returns (uint256) fn = (x % 2 == 0) ? _f1 : _f2;\n    orders[x].amount = 10;\n    orders[x].epoch = fn(x);\n    if (x == 3) { delete orders[x]; }\n    out = orders[x].epoch + lock;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('fn-ptr-external-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external view returns (uint256) {\n    function (uint256) external view returns (uint256) fn = this.checked;\n    return fn(x);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] only internal function pointer locals are supported, found external'),
        ('fn-ptr-uninitialized-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    function (uint256) internal pure returns (uint256) fn;\n    return fn(x);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] uninitialized function pointer locals are outside this slice'),
        ('fn-ptr-reassigned-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function _f1(uint256 a) internal pure returns (uint256) { return a + 1; }\n  function _f2(uint256 a) internal pure returns (uint256) { return a + 2; }\n  function checked(uint256 x) external pure returns (uint256) {\n    function (uint256) internal pure returns (uint256) fn = _f1;\n    fn = _f2;\n    return fn(x);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] reassigned function pointer locals are outside this slice'),
        ('delete-mapping-struct-opaque-member-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  struct S { uint256 a; uint256[] dyn; }\n  mapping(uint256 => S) private m;\n  function checked(uint256 x) external returns (uint256) {\n    delete m[x];\n    return m[x].a;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'IndexAccess: [solidity-import:unsupported] cannot delete mapping struct with opaque members'),
        ('modifier-multiple-placeholders-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  modifier m() { _; _; }\n  function checked(uint256 x) external m pure returns (uint256) { return x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'ModifierDefinition: [solidity-import:unsupported] only a single top-level _; placeholder is supported in modifiers'),
        ('modifier-nested-placeholder-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  modifier m(uint256 x) { if (x > 0) { _; } }\n  function checked(uint256 x) external m(x) pure returns (uint256) { return x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'ModifierDefinition: [solidity-import:unsupported] only a single top-level _; placeholder is supported in modifiers'),
        ('empty-array-return-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256) external pure returns (address[] memory) {}\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('empty-array-return-nonempty-body-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function checked(uint256 x) external returns (address[] memory) { v = x; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionDefinition: [solidity-import:unsupported] an explicit root return is required'),
        ('empty-array-return-narrow-elem-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256) external pure returns (uint8[] memory) {}\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] unsupported empty-body root return type uint8[]'),
        ('empty-array-return-with-modifier-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  modifier m() { _; }\n  function checked(uint256) external m pure returns (address[] memory) {}\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] unsupported empty-body root return type address[]'),
        ('bytes-param-calldata-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(bytes calldata b) external pure returns (uint256) { return b.length; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('bytes-param-unnamed-empty-array-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(bytes calldata) external pure returns (uint256[] memory) {}\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('bytes-param-memory-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(bytes memory b) external pure returns (uint256) { return b.length; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] unsupported location memory for bytes'),
        ('bytes-param-value-use-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(bytes calldata b) external pure returns (uint256) { bytes calldata c = b; return c.length; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Identifier: [solidity-import:unsupported] storage or memory path used as a value'),
        ('overload-const-error-cond-tuple-tload-accepted',
         "pragma solidity 0.8.34;\nuint256 constant ZERO_CONST = 0;\ncontract C {\n  error BoundErr(address who, uint8 maxB, uint256 z);\n  uint256 private saved;\n  function _tloadSlot(uint256 slot) internal view returns (bool v) {\n    assembly (\"memory-safe\") { v := tload(slot) }\n  }\n  function _ setVal(uint256 a) internal { _setVal(a, true); }\n  function _setVal(uint256 a, bool bump) internal { saved = bump ? a + 1 : a; }\n  function checked(uint256 x) external returns (uint256) {\n    if (x == 99) revert BoundErr(address(0), type(uint8).max, ZERO_CONST);\n    _ setVal(x);\n    (uint256 lo, uint256 hi) = x < 10 ? (0 days, 1 days) : (1 days, 7 days);\n    bool locked = _tloadSlot(x);\n    return saved + lo + hi + (locked ? 1 : 0);\n  }\n}\n".replace('_ setVal', '_setVal'),
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('overload-root-collision-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) { return x; }\n  function checked(uint256 x, uint256 y) external pure returns (uint256) { return x + y; }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionDefinition: [solidity-import:unsupported] root function name collision: C.checked; import overloaded roots in separate slices'),
        ('custom-error-nonconst-cast-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  error Failure(address who);\n  function checked(uint256 x) external pure returns (uint256) {\n    if (x > 0) revert Failure(address(uint160(x)));\n    return 0;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCall: [solidity-import:unsupported] custom-error arguments currently require literals or scalar bindings'),
        ('cond-tuple-stateful-component-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function _bump() internal returns (uint256) { v += 1; return v; }\n  function checked(uint256 x) external returns (uint256) {\n    (uint256 a, uint256 b) = (x == 0) ? (_bump(), uint256(1)) : (uint256(2), uint256(3));\n    return a + b;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCall: [solidity-import:unsupported] stateful or assignment expression in multi-return tuple requires explicit evaluation-order support'),
        ('struct-fixed-array-and-fixed-return-accepted',
         "pragma solidity 0.8.34;\ncontract C {\n  struct Pos { uint128 credit; uint128[4] collateral; uint16[3] fees; }\n  mapping(bytes32 => mapping(address => Pos)) private pos;\n  function checked(uint256 x) external returns (uint256[2] memory) {\n    bytes32 id = bytes32(uint256(1));\n    uint256 idx = x % 4;\n    pos[id][msg.sender].credit = uint128(x + 1);\n    pos[id][msg.sender].collateral[idx] = uint128(x + 5);\n    uint128[4] memory snap = pos[id][msg.sender].collateral;\n    pos[id][msg.sender].fees[0] = uint16((x % 50) + 1);\n    return [uint256(snap[idx]), uint256(pos[id][msg.sender].fees[0]) + pos[id][msg.sender].credit];\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('delete-mapping-struct-with-fixed-array-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  struct S { uint256 a; uint128[4] arr; }\n  mapping(uint256 => S) private m;\n  function checked(uint256 x) external returns (uint256) {\n    delete m[x];\n    return m[x].a;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'IndexAccess: [solidity-import:unsupported] cannot delete mapping struct with fixed-array members'),
        ('delete-whole-struct-fixed-array-member-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  struct S { uint256 a; uint128[4] arr; }\n  mapping(uint256 => S) private m;\n  function checked(uint256 x) external returns (uint256) {\n    delete m[x].arr;\n    return m[x].a;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] struct fixed array member arr requires an element index'),
        ('fixed-array-return-stateful-component-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 private v;\n  function _bump() internal returns (uint256) { v += 1; return v; }\n  function checked(uint256) external returns (uint256[2] memory) {\n    return [_bump(), uint256(1)];\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCall: [solidity-import:unsupported] stateful or assignment expression in inline return array requires explicit evaluation-order support'),
        ('fixed-array-return-non-snapshot-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  mapping(uint256 => uint16[3]) private m;\n  function checked(uint256 x) external view returns (uint16[3] memory) {\n    return m[x];\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'IndexAccess: [solidity-import:unsupported] fixed-size array return requires an inline array or fixed array snapshot'),
        ('msg-data-and-enum-positive',
         "pragma solidity 0.8.34;\nabstract contract ContextBase {\n  function _msgData() internal view virtual returns (bytes calldata) { return msg.data; }\n}\ncontract C is ContextBase {\n  enum Mode { Disabled, Standard, Turbo }\n  function echoMsgData() external view returns (bytes memory) { return _msgData(); }\n  function checked(Mode m, uint256 x) external view returns (Mode, uint256) {\n    Mode next = m == type(Mode).max ? type(Mode).min : Mode(uint8(m) + 1);\n    Mode picked = Mode(x % 3);\n    return (picked, uint256(uint8(next)) + _msgData().length + msg.data.length);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('msg-data-return-with-params-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256) external pure returns (bytes memory) {\n    return msg.data;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] unsupported message context member data'),
        ('msg-data-helper-multi-stmt-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function _msgData() internal pure returns (bytes calldata) {\n    uint256 x = 1;\n    x;\n    return msg.data;\n  }\n  function checked(uint256) external pure returns (uint256) {\n    return _msgData().length;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionDefinition: [solidity-import:unsupported] msg.data helper must be a single return statement'),
        ('enum-fallible-cast-in-abi-encode-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  enum Mode { A, B }\n  function checked(uint256 x) external pure returns (bytes32) {\n    return keccak256(abi.encode(Mode(x)));\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCall: [solidity-import:unsupported] fallible enum conversion in ABI encoding argument is unsupported'),
        ('exp-and-bitwise-shift-positive',
         "pragma solidity 0.8.34;\ncontract C {\n  uint128 private bmp;\n  int256 private s;\n  function checked(uint256 x) external returns (uint256) {\n    uint256 p = 10 ** (x % 6) + (x % 100) ** 2;\n    uint8 w;\n    unchecked { w = uint8(x + 2) ** uint8((x % 4) + 1); }\n    bmp |= uint128(1 << (x % 16));\n    bmp ^= ~uint128(x & 0xff);\n    bmp >>= uint8((x % 2) + 1);\n    bmp <<= uint8(x % 3);\n    s = -int256((x % 64) + 8);\n    s >>= 1;\n    s /= int256(2);\n    p /= ((x % 3) + 1);\n    p %= 97;\n    return p + uint256(bmp) + uint256(w) + uint256(s < 0 ? -s : s);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('checked-exp-dynamic-base-and-exp-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    return x ** x;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'BinaryOperation: [solidity-import:unsupported] checked exponentiation with dynamic base and exponent is outside this slice'),
        ('signed-compound-mod-assign-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    int256 s = int256(x);\n    s %= int256(7);\n    return uint256(s);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Assignment: [solidity-import:unsupported] unsupported compound assignment operator %='),
        ('int-const-shift-intermediate-overflow-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    return ((1 << 256) >> 1) + x;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'BinaryOperation: [solidity-import:unsupported] unsupported operand type int_const'),
        ('while-clz-and-struct-loc-positive',
         "pragma solidity 0.8.34;\ncontract C {\n  struct Item { uint256 v; bool ok; }\n  struct Pack { uint256 head; Item[] items; }\n  function _msb(uint256 x) internal pure returns (uint8 r) {\n    assembly (\"memory-safe\") { r := sub(255, clz(x)) }\n  }\n  function _clear(uint256 b, uint8 i) internal pure returns (uint256) { return b & ~(1 << i); }\n  function _eval(Pack memory p) internal pure returns (uint256) {\n    Pack memory aliasP = p;\n    if (aliasP.items.length > 0) {\n      Item memory m = aliasP.items[0];\n      return aliasP.head + (m.ok ? m.v : 0);\n    }\n    return aliasP.head;\n  }\n  function checked(Pack calldata p, uint256 x) external pure returns (uint256) {\n    uint256 acc = _eval(p);\n    if (p.items.length > 0) {\n      Item calldata cd = p.items[p.items.length - 1];\n      Item memory cp = p.items[0];\n      acc += (cd.ok ? cd.v : 0) + cp.v;\n    }\n    uint256 w = x;\n    while (w != 0) {\n      uint8 i = _msb(w);\n      acc += i;\n      w = _clear(w, i);\n    }\n    uint256 u = x;\n    while (u != 0) {\n      acc += 1;\n      u &= (u - 1);\n    }\n    uint256 b = 128;\n    while (b > 0) {\n      acc += b;\n      b >>= 1;\n    }\n    return acc;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('while-non-decreasing-step-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    uint256 v = x;\n    while (v != 0) {\n      v -= 1;\n    }\n    return v;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Assignment: [solidity-import:unsupported] while loop update is not a recognized bounded bit-clearing or right-shift step'),
        ('while-return-inside-loop-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    uint256 v = x;\n    while (v != 0) {\n      return v;\n    }\n    return 0;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'WhileStatement: [solidity-import:unsupported] return inside a while loop is unsupported'),
        ('while-prefix-writes-loop-var-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external pure returns (uint256) {\n    uint256 v = x;\n    while (v != 0) {\n      v = 1;\n      v >>= 1;\n    }\n    return v;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'ExpressionStatement: [solidity-import:unsupported] a while loop variable may only be updated in the final loop statement'),
        ('struct-local-reassigned-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  struct S { uint256 a; }\n  function checked(S calldata p) external pure returns (uint256) {\n    S memory s = p;\n    s = p;\n    return s.a;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'VariableDeclaration: [solidity-import:unsupported] reassigned struct locals are outside this slice'),
        ('immutable-state-var-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  uint256 internal immutable IMM = 7;\n  function checked(uint256 x) external view returns (uint256) {\n    return x + IMM;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Identifier: [solidity-import:unsupported] immutable state variable IMM is outside this slice'),
        ('yul-builtins-and-encode-selector-positive',
         "pragma solidity 0.8.34;\ninterface IToken { function transfer(address to, uint256 amount) external returns (bool); }\ncontract C {\n  function _mix(int256 a, int256 b, uint256 w) internal view returns (uint256 r) {\n    assembly (\"memory-safe\") {\n      r := xor(add(add(sdiv(a, b), smod(a, b)), add(add(shl(1, slt(a, b)), sgt(a, b)), exp(2, and(w, 7)))), xor(add(byte(and(w, 31), w), signextend(0, w)), xor(add(add(caller(), address()), add(timestamp(), number())), chainid())))\n    }\n  }\n  function checked(uint256 x) external view returns (uint256) {\n    IToken tok = IToken(address(uint160(x + 1)));\n    bytes memory data = abi.encodeWithSelector(IToken.transfer.selector, address(uint160(x)), x);\n    bytes32 d1 = keccak256(data);\n    bytes32 d2 = keccak256(abi.encodeWithSelector(tok.transfer.selector, msg.sender, x));\n    bytes32 d3 = keccak256(abi.encodeWithSelector(this.checked.selector, x));\n    bytes32 d4 = keccak256(abi.encodePacked(IToken.transfer.selector, tok.transfer.selector, this.checked.selector, x));\n    return uint256(d1) ^ uint256(d2) ^ uint256(d3) ^ uint256(d4) ^ _mix(-int256(x + 5), int256((x % 7) + 1), x);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         None),
        ('selector-state-var-receiver-rejected',
         "pragma solidity 0.8.34;\ninterface IToken { function transfer(address to, uint256 amount) external returns (bool); }\ncontract C {\n  IToken public token;\n  function checked(uint256 x) external view returns (bytes32) {\n    return keccak256(abi.encodeWithSelector(token.transfer.selector, address(0), x));\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'Identifier: [solidity-import:unsupported] selector receiver must be a contract/interface type, this, or a local/parameter'),
        ('selector-standalone-expr-rejected',
         "pragma solidity 0.8.34;\ninterface IToken { function transfer(address to, uint256 amount) external returns (bool); }\ncontract C {\n  function checked(uint256) external pure returns (uint32) {\n    return uint32(IToken.transfer.selector);\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] function .selector member access is outside this slice'),
        ('abi-encode-with-selector-expr-rejected',
         "pragma solidity 0.8.34;\ninterface IToken { function transfer(address to, uint256 amount) external returns (bool); }\ncontract C {\n  function _sink(bytes memory) internal pure returns (uint256) { return 1; }\n  function checked(uint256 x) external pure returns (uint256) {\n    return _sink(abi.encodeWithSelector(IToken.transfer.selector, address(0), x));\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] abi.encodeWithSelector is only supported as a byte buffer'),
        ('abi-decode-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256) external pure returns (uint256) {\n    return abi.decode(msg.data, (uint256));\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] abi.decode is outside this slice'),
        ('address-code-read-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external view returns (uint256) {\n    return address(uint160(x)).code.length;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] external contract code reads are outside this slice'),
        ('external-call-options-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external returns (uint256) {\n    (bool ok, ) = address(uint160(x)).call{value: 0}(\"\");\n    return ok ? 1 : 0;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'FunctionCallOptions: [solidity-import:unsupported] external contract calls are outside this slice'),
        ('low-level-call-rejected',
         "pragma solidity 0.8.34;\ncontract C {\n  function checked(uint256 x) external view returns (uint256) {\n    (bool ok, ) = address(uint160(x)).staticcall(\"\");\n    return ok ? 1 : 0;\n  }\n}\n",
         None,
         '{ evmVersion := "osaka", viaIR := true, optimizerRuns := some 466, bytecodeHash := "none" }',
         'MemberAccess: [solidity-import:unsupported] external contract calls are outside this slice'),
    ]
    for name, source_text, dep_text, profile_text, expected in solc_0810_cases:
        if args.only and args.only not in name:
            continue
        directory = output / name
        directory.mkdir()
        (directory / 'Fixture.sol').write_text(source_text)
        if dep_text is not None:
            (directory / 'Dep.sol').write_text(dep_text)
        fn_sig = (
            'checked(bytes)' if name.startswith('bytes-param-')
            else 'checked(uint256)\n  function checked(uint256, uint256)' if name == 'overload-root-collision-rejected'
            else 'echoMsgData()\n  function checked(Mode,uint256)' if name == 'msg-data-and-enum-positive'
            else 'checked(Pack,uint256)' if name == 'while-clz-and-struct-loc-positive'
            else 'checked(S)' if name == 'struct-local-reassigned-rejected'
            else 'checked(uint256)'
        )
        driver = directory / 'Check.lean'
        driver.write_text(f'''import Compiler.SolidityImport.Import
solidity_import tested from "{directory}" entry "Fixture.sol"
  using {profile_text}
  contract C
  function {fn_sig}
''')
        artifact = directory / 'Check.olean'
        result = subprocess.run(['lake', 'env', 'lean', str(driver), '-o', str(artifact)],
                                cwd=root, text=True, capture_output=True, timeout=120)
        text = result.stdout + result.stderr
        (directory / 'check.log').write_text(text)
        if expected is None:
            if result.returncode or not artifact.exists():
                raise RuntimeError(f'{name}: positive control failed\n{text}')
        elif result.returncode == 0 or artifact.exists() or expected not in text:
            raise RuntimeError(f'{name}: expected rejection {expected!r}\n{text}')
        print(f'pass storage-{name}', flush=True)
    print(output)


if __name__ == '__main__':
    main()

