import Contracts.Common

namespace Contracts

open Verity hiding pure bind
open Verity.EVM.Uint256
open Verity.Stdlib.Math

@[simp] def boolToWord (b : Bool) : Uint256 :=
  if b then 1 else 0

verity_contract ERC721 where
  storage
    owner : Address := slot 0
    totalSupply : Uint256 := slot 1
    nextTokenId : Uint256 := slot 2
    balances : Address → Uint256 := slot 3
    owners : Uint256 → Uint256 := slot 4
    tokenApprovals : Uint256 → Uint256 := slot 5
    operatorApprovals : Address → Address → Uint256 := slot 6

  constructor (initialOwner : Address) := do
    setStorageAddr owner initialOwner
    setStorage totalSupply 0
    setStorage nextTokenId 0

  function balanceOf (addr : Address) : Uint256 := do
    let currentBalance ← getMapping balances addr
    return currentBalance

  function ownerOf (tokenId : Uint256) : Address := do
    let ownerWord ← getMappingUint owners tokenId
    require (ownerWord != 0) "Token does not exist"
    return wordToAddress ownerWord

  function getApproved (tokenId : Uint256) : Address := do
    let ownerWord ← getMappingUint owners tokenId
    require (ownerWord != 0) "Token does not exist"
    let approvedAddr ← getMappingUintAddr tokenApprovals tokenId
    return approvedAddr

  function isApprovedForAll (ownerAddr : Address, operator : Address) : Bool := do
    let flag ← getMapping2 operatorApprovals ownerAddr operator
    return flag != 0

  function approve (approved : Address, tokenId : Uint256) : Unit := do
    let sender ← msgSender
    let ownerWord ← getMappingUint owners tokenId
    require (ownerWord != 0) "Token does not exist"
    let senderWord := addressToWord sender
    require (senderWord == ownerWord) "Not token owner"
    setMappingUintAddr tokenApprovals tokenId approved

  function setApprovalForAll (operator : Address, approved : Bool) : Unit := do
    let sender ← msgSender
    setMapping2 operatorApprovals sender operator (boolToWord approved)

  function mint (toAddr : Address) : Uint256 := do
    let sender ← msgSender
    let currentOwner ← getStorageAddr owner
    require (sender == currentOwner) "Caller is not the owner"
    require (toAddr != zeroAddress) "Invalid recipient"

    let tokenId ← getStorage nextTokenId
    let currentOwnerWord ← getMappingUint owners tokenId
    require (currentOwnerWord == 0) "Token already minted"

    let recipientBalance ← getMapping balances toAddr
    let newRecipientBalance ← requireSomeUint (safeAdd recipientBalance 1) "Balance overflow"

    let currentSupply ← getStorage totalSupply
    let newSupply ← requireSomeUint (safeAdd currentSupply 1) "Supply overflow"

    setMappingUintAddr owners tokenId toAddr
    setMapping balances toAddr newRecipientBalance
    setStorage totalSupply newSupply
    setStorage nextTokenId (add tokenId 1)
    return tokenId

  function transferFrom (fromAddr : Address, toAddr : Address, tokenId : Uint256) : Unit := do
    let sender ← msgSender
    require (toAddr != zeroAddress) "Invalid recipient"

    let ownerWord ← getMappingUint owners tokenId
    require (ownerWord != 0) "Token does not exist"

    let fromWord := addressToWord fromAddr
    require (ownerWord == fromWord) "From is not owner"

    let approvedWord ← getMappingUint tokenApprovals tokenId
    let operatorWord ← getMapping2 operatorApprovals fromAddr sender
    let senderWord := addressToWord sender
    let authorized := (sender == fromAddr) || (approvedWord == senderWord) || (operatorWord != 0)
    require authorized "Not authorized"

    if fromAddr == toAddr then
      pure ()
    else
      let fromBalance ← getMapping balances fromAddr
      require (fromBalance >= 1) "Insufficient balance"
      let toBalance ← getMapping balances toAddr
      let newToBalance ← requireSomeUint (safeAdd toBalance 1) "Balance overflow"
      setMapping balances fromAddr (sub fromBalance 1)
      setMapping balances toAddr newToBalance

    setMappingUintAddr owners tokenId toAddr
    setMappingUintAddr tokenApprovals tokenId zeroAddress

namespace ERC721

-- `constructor` is generated by `verity_contract` (verity#2465).

abbrev boolToWord : Bool → Uint256 := Contracts.boolToWord

def isOwner : Contract Bool := do
  let sender ← msgSender
  let currentOwner ← getStorageAddr owner
  return sender == currentOwner

def onlyOwner : Contract Unit := do
  let ownerCheck ← isOwner
  require ownerCheck "Caller is not the owner"

end ERC721

end Contracts
