import Compiler.CompilationModel.DynamicData
import Compiler.Proofs.YulGeneration.Backends.EvmYulLeanPanic

/-!
Byte-level observation of the compiler's panic payload instructions.

This deliberately small execution fragment reads the emitted Yul AST and uses
EVMYulLean's byte-addressed memory operations. It supports constant words,
`shl`, memory stores, and a terminal `revert`; unsupported syntax returns
`none`. Unlike the abstract IR interpreter and the native Yul exception, it
retains the bytes selected by `revert`. It is not a whole-contract interpreter
or a proof about solc-generated bytecode.
-/

namespace Compiler.Proofs.YulGeneration

open Compiler.Yul
open Compiler.CompilationModel
open Compiler.Proofs.YulGeneration.Backends.Panic

private def evalPanicWord : YulExpr → Option EvmYul.UInt256
  | .lit value | .hex value => some (EvmYul.UInt256.ofNat value)
  | .call "shl" [shift, value] => do
      let shift ← evalPanicWord shift
      let value ← evalPanicWord value
      pure (EvmYul.UInt256.shiftLeft value shift)
  | _ => none

/-- Execute the constant-memory panic fragment and retain the actual revert
bytes. A missing/unsupported terminator or instruction fails closed. -/
def observePanicPayloadBytes (state : EvmYul.MachineState) :
    List YulStmt → Option ByteArray
  | .exprStmt (.call "mstore" [offset, value]) :: rest => do
      let offset ← evalPanicWord offset
      let value ← evalPanicWord value
      observePanicPayloadBytes (state.mstore offset value) rest
  | [.exprStmt (.call "revert" [offset, size])] => do
      let offset ← evalPanicWord offset
      let size ← evalPanicWord size
      pure (state.evmRevert offset size).H_return
  | _ => none

/-- Connect the actual compiler-emitted AST to the EVM memory operations.
In particular, the offset and length are read from `solidityPanicPayload`. -/
theorem observePanicPayloadBytes_eq_machineState
    (state : EvmYul.MachineState) (code : Nat) :
    observePanicPayloadBytes state (solidityPanicPayload code) =
      some (((state.mstore (EvmYul.UInt256.ofNat 0)
          (EvmYul.UInt256.ofNat (0x4e487b71 * 2 ^ 224))).mstore
            (EvmYul.UInt256.ofNat 4) (EvmYul.UInt256.ofNat code)).evmRevert
              (EvmYul.UInt256.ofNat 0) (EvmYul.UInt256.ofNat 36)).H_return := by
  rfl

/-- The actual emitted panic sequence returns the selector followed by the
32-byte encoding of the code, independently of the initial memory contents.
As in the EVM, the numeric code is interpreted as a 256-bit word. -/
theorem observePanicPayloadBytes_solidityPanicPayload
    (state : EvmYul.MachineState) (code : Nat) :
    observePanicPayloadBytes state (solidityPanicPayload code) =
      some (expectedPanicBytes (EvmYul.UInt256.ofNat code)) := by
  rw [observePanicPayloadBytes_eq_machineState, machineState_panicPayload_bytes]

/-- The emitted panic sequence returns exactly 36 bytes. -/
theorem observePanicPayloadBytes_solidityPanicPayload_size
    (state : EvmYul.MachineState) (code : Nat) :
    (observePanicPayloadBytes state (solidityPanicPayload code)).map ByteArray.size =
      some 36 := by
  simp [observePanicPayloadBytes_solidityPanicPayload, expectedPanicBytes_size]

/-- Byte-accurate payload for the typed overflow/underflow panic. -/
theorem observePanicPayloadBytes_arithmeticOverflow
    (state : EvmYul.MachineState) :
    observePanicPayloadBytes state
        (solidityPanicPayload Verity.Core.PanicCode.arithmeticOverflow.toNat) =
      some (expectedPanicBytes (EvmYul.UInt256.ofNat 0x11)) := by
  exact observePanicPayloadBytes_solidityPanicPayload state 0x11

/-- Byte-accurate payload for the typed division-by-zero panic. -/
theorem observePanicPayloadBytes_divisionByZero
    (state : EvmYul.MachineState) :
    observePanicPayloadBytes state
        (solidityPanicPayload Verity.Core.PanicCode.divisionByZero.toNat) =
      some (expectedPanicBytes (EvmYul.UInt256.ofNat 0x12)) := by
  exact observePanicPayloadBytes_solidityPanicPayload state 0x12

end Compiler.Proofs.YulGeneration
