/-
  Compiler.CompilationModel: Declarative compilation-model facade

  This top-level module re-exports the focused CompilationModel submodules.
  Implementation details now live under `Compiler/CompilationModel/*`.
-/
import Compiler.CompilationModel.Types
import Compiler.CompilationModel.AbiHelpers
import Compiler.CompilationModel.AbiTypeLayout
import Compiler.CompilationModel.AdtStorageLayout
import Compiler.CompilationModel.AbiEncoding
import Compiler.CompilationModel.DynamicData
import Compiler.CompilationModel.EcmAxiomCollection
import Compiler.CompilationModel.EventEmission
import Compiler.CompilationModel.EventAbiHelpers
import Compiler.CompilationModel.InternalArgs
import Compiler.CompilationModel.InternalNaming
import Compiler.CompilationModel.IssueRefs
import Compiler.CompilationModel.LayoutReport
import Compiler.CompilationModel.LayoutValidation
import Compiler.CompilationModel.LogicalPurity
import Compiler.CompilationModel.MappingWrites
import Compiler.CompilationModel.ScopeValidation
import Compiler.CompilationModel.StorageWrites
import Compiler.CompilationModel.TrustSurface
import Compiler.CompilationModel.YulImporter
import Compiler.CompilationModel.UsageAnalysis
import Compiler.CompilationModel.ValidationCalls
import Compiler.CompilationModel.ValidationEvents
import Compiler.CompilationModel.ValidationHelpers
import Compiler.CompilationModel.ValidationInterop
import Compiler.CompilationModel.SelectorInteropHelpers
import Compiler.CompilationModel.ExpressionCompile
import Compiler.CompilationModel.Validation
import Compiler.CompilationModel.Compile
import Compiler.CompilationModel.ParamLoading
import Compiler.CompilationModel.Dispatch
import Compiler.CompilationModel.LayoutReport
import Compiler.CompilationModel.LayoutCompatibilityReport
import Compiler.CompilationModel.TrustSurface
