import Compiler.Modules.Calls
import Compiler.Modules.Callbacks
import Compiler.Modules.ERC4626
import Compiler.Modules.ERC20
import Compiler.Modules.Hashing
import Compiler.Modules.Oracle
import Compiler.Modules.Precompiles
import Compiler.Modules.Create2SSTORE2
import Compiler.Modules.CodeData
