#!/usr/bin/env python3
"""Generate / check the storage layout audit artifacts (issue #1897).

The Lean executable `verity-storage-layout-report` is the source of truth: it
emits the storage layout JSON for `Compiler.Specs.allSpecs` (canonical
production contract surface) to stdout. This script:

  * pretty-prints that JSON into `artifacts/storage_layout_report.json`
    (machine-readable, sorted, indent=2 — matching the convention used by
    other audit artifacts);
  * renders the human-readable Markdown summary into
    `artifacts/STORAGE_LAYOUT_SUMMARY.md`; and
  * in `--check` mode, fails on drift between the committed artifacts and
    what would be produced now.

Usage:
    python3 scripts/generate_storage_layout_report.py            # regen both
    python3 scripts/generate_storage_layout_report.py --check    # CI drift gate
    python3 scripts/generate_storage_layout_report.py --no-lean  # skip Lean
                                                                 # (re-render
                                                                 # summary from
                                                                 # committed
                                                                 # JSON only)

`--no-lean` is the mode used by `make check`, which does not run Lean. The
Lean-side drift gate runs as part of `lake build` via
`Compiler.StorageLayoutReportTest`.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from property_utils import ROOT

DEFAULT_JSON = ROOT / "artifacts" / "storage_layout_report.json"
DEFAULT_SUMMARY = ROOT / "artifacts" / "STORAGE_LAYOUT_SUMMARY.md"
LEAN_EXE = "verity-storage-layout-report"


def fetch_lean_json() -> dict:
    """Invoke the Lean exe and parse its stdout as JSON."""
    result = subprocess.run(
        ["lake", "exe", LEAN_EXE],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def render_json(payload: dict) -> str:
    return json.dumps(payload, sort_keys=True, indent=2) + "\n"


def load_committed_json(json_path: Path) -> dict:
    if not json_path.exists():
        raise SystemExit(
            f"Missing storage layout artifact: {json_path}\n"
            f"Regenerate with: python3 scripts/generate_storage_layout_report.py"
        )
    return json.loads(json_path.read_text(encoding="utf-8"))


def _fmt_slots(values: list[int]) -> str:
    if not values:
        return "—"
    return ", ".join(str(v) for v in values)


def _fmt_packed(packed: dict | None) -> str:
    if not packed:
        return "—"
    return f"offset {packed['offset']}, width {packed['width']}"


def _fmt_type(ty: dict) -> str:
    kind = ty.get("kind", "unknown")
    if kind == "uint256":
        return "uint256"
    if kind == "address":
        return "address"
    if kind == "adt":
        return f"adt {ty.get('name', '?')} (max {ty.get('maxFields', '?')} fields)"
    if kind == "dynamicArray":
        return f"dynamic array of {ty.get('elemType', '?')}"
    if kind == "mapping":
        keys = ", ".join(ty.get("keys", []))
        value = ty.get("valueKind", "uint256")
        return f"mapping({keys} => {value})"
    if kind == "mappingStruct":
        keys = ", ".join(ty.get("keys", []))
        members = ty.get("members", [])
        return f"mapping({keys} => struct[{len(members)}])"
    return kind


def _struct_members_table(members: list[dict]) -> list[str]:
    rows: list[str] = [
        "  | Member | Type | Word offset | Packed bits |",
        "  | ------ | ---- | ----------- | ----------- |",
    ]
    for m in members:
        rows.append(
            f"  | `{m['name']}` | {m['type']} | {m['wordOffset']} | "
            f"{_fmt_packed(m.get('packedBits'))} |"
        )
    return rows


def render_summary(report: dict) -> str:
    contracts = report.get("contracts", [])
    lines: list[str] = [
        "# Storage Layout Summary",
        "",
        "_Auto-generated by `scripts/generate_storage_layout_report.py` from",
        "`artifacts/storage_layout_report.json`. Do not edit by hand; rerun",
        "the generator after any change to a production storage layout._",
        "",
        "Source of truth: `Compiler.Specs.allSpecs` (canonical production",
        "contract surface). See `AUDIT.md` for the audit-artifact registry",
        "and issue #1897 for the migration-review motivation.",
        "",
        "## Non-alias certificate justifications (#1966)",
        "",
        "Each pairwise non-alias claim in the per-contract sections below",
        "is tagged with a *justification kind*. The justification tells a",
        "downstream proof how to discharge the obligation:",
        "",
        "- `distinctScalarSlots` — both families are scalar (uint256 /",
        "  address / ADT) at *distinct* declared storage slots. The claim",
        "  reduces to `aSlot ≠ bSlot` and is decidable by `decide` against",
        "  the certificate.",
        "- `keccakDomainScalar` — one family is keccak-derived (mapping,",
        "  dynamic array, mapping-struct), the other a scalar at a small",
        "  declared slot. Discharged by the standard keccak preimage",
        "  assumption that `keccak256` digests do not collide with any",
        "  slot below `maxDeclaredSlot` (named here as",
        "  `keccak_above_max_declared_slot`).",
        "- `keccakPreimageDistinct` — both families are keccak-derived",
        "  with *disjoint* preimage shapes (their `keccakPreimage`",
        "  strings differ). Discharged by a `keccak256` injectivity",
        "  assumption named after the concrete preimage families.",
        "",
        "Together these obligations replace a single global",
        "`Loc.slot_inj` boundary with per-family local axioms plus a",
        "decidable finite subset.",
        "",
        f"Contracts covered: **{len(contracts)}**",
        "",
    ]

    for spec in contracts:
        name = spec.get("contract", "?")
        ns = spec.get("storageNamespace")
        lines.append(f"## {name}")
        lines.append("")
        if ns is None:
            lines.append("- Storage namespace: _none_ (slots start at 0)")
        else:
            lines.append(f"- Storage namespace base: `{ns}`")
        reserved = spec.get("reservedSlotRanges", [])
        if reserved:
            ranges = ", ".join(f"[{r['start']}..{r['end']}]" for r in reserved)
            lines.append(f"- Reserved slot ranges: {ranges}")
        aliases = spec.get("slotAliasRanges", [])
        if aliases:
            ranges = ", ".join(
                f"[{r['sourceStart']}..{r['sourceEnd']}] -> {r['targetStart']}+"
                for r in aliases
            )
            lines.append(f"- Slot alias ranges: {ranges}")
        fields = spec.get("fields", [])
        lines.append(f"- Fields: {len(fields)}")
        lines.append("")
        if fields:
            lines.extend(
                [
                    "| Field | Canonical slot | Declared slot | Alias slots | Type | Packed bits |",
                    "| ----- | -------------- | ------------- | ----------- | ---- | ----------- |",
                ]
            )
            for f in fields:
                declared = "auto" if f.get("declaredSlot") is None else f["declaredSlot"]
                lines.append(
                    f"| `{f['name']}` | {f['canonicalSlot']} | {declared} | "
                    f"{_fmt_slots(f.get('effectiveAliasSlots', []))} | "
                    f"{_fmt_type(f.get('type', {}))} | "
                    f"{_fmt_packed(f.get('packedBits'))} |"
                )
            for f in fields:
                members = f.get("type", {}).get("members") or []
                if members:
                    lines.append("")
                    lines.append(f"- `{f['name']}` struct members:")
                    lines.append("")
                    lines.extend(_struct_members_table(members))

        # Non-alias certificate (#1966): per-contract storage families plus
        # the pairwise non-alias claims and the justification each demands.
        families = spec.get("storageFamilies", [])
        claims = spec.get("nonAliasClaims", [])
        if families:
            lines.append("")
            lines.append("### Non-alias certificate (#1966)")
            lines.append("")
            lines.append(
                "Each storage field is classified as a *family* — the set of"
                " runtime storage locations it can occupy. Scalar families"
                " collapse to a single declared slot; keccak-derived"
                " families (mappings, dynamic arrays, mapping-structs) span"
                " a preimage-parameterised neighbourhood. The pairwise"
                " non-alias claims below are the obligations a downstream"
                " proof must discharge to replace a global"
                " keccak-injectivity assumption with per-family local"
                " obligations."
            )
            lines.append("")
            lines.extend([
                "| Family | Kind | Root slot | Keccak preimage | Struct word range |",
                "| ------ | ---- | --------- | --------------- | ----------------- |",
            ])
            for fam in families:
                preimage = fam.get("keccakPreimage")
                preimage_cell = "—" if preimage is None else f"`{preimage}`"
                rng = fam.get("structWordRange")
                rng_cell = "—" if rng is None else f"[{rng['min']}..{rng['maxInclusive']}]"
                lines.append(
                    f"| `{fam['name']}` | {fam['kind']} | {fam['rootSlot']} | {preimage_cell} | {rng_cell} |"
                )
            if claims:
                lines.append("")
                lines.append("**Non-alias claims** (grouped by justification):")
                lines.append("")
                grouped: dict[str, list[dict]] = {}
                for c in claims:
                    grouped.setdefault(c["justification"], []).append(c)
                for justification, group in sorted(grouped.items()):
                    lines.append(f"- `{justification}` ({len(group)} pair{'s' if len(group) != 1 else ''}):")
                    for c in group:
                        lines.append(
                            f"  - `{c['a']}` (slot {c['aSlot']}) ⟂ `{c['b']}` (slot {c['bSlot']})"
                        )
            else:
                lines.append("")
                lines.append("_No non-alias claims (single-field contract)._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def check_drift(rendered_json: str, rendered_summary: str,
                json_path: Path, summary_path: Path) -> int:
    if not json_path.exists():
        print(f"Missing storage layout artifact: {json_path}", file=sys.stderr)
        return 1
    if json_path.read_text(encoding="utf-8") != rendered_json:
        print(
            "Storage layout JSON is stale. Regenerate with:\n"
            "  python3 scripts/generate_storage_layout_report.py",
            file=sys.stderr,
        )
        return 1
    if not summary_path.exists():
        print(f"Missing storage layout summary: {summary_path}", file=sys.stderr)
        return 1
    if summary_path.read_text(encoding="utf-8") != rendered_summary:
        print(
            "Storage layout summary is stale. Regenerate with:\n"
            "  python3 scripts/generate_storage_layout_report.py",
            file=sys.stderr,
        )
        return 1
    print(f"Storage layout artifacts are up to date: {json_path}, {summary_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--json",
        type=Path,
        default=DEFAULT_JSON,
        help="Path to the JSON artifact (default: artifacts/storage_layout_report.json)",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=DEFAULT_SUMMARY,
        help="Path to the Markdown summary (default: artifacts/STORAGE_LAYOUT_SUMMARY.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed artifacts are stale vs current Lean output",
    )
    parser.add_argument(
        "--no-lean",
        action="store_true",
        help="Use committed JSON as input; do not invoke Lean (used by `make check`)",
    )
    args = parser.parse_args()

    if args.no_lean:
        payload = load_committed_json(args.json)
    else:
        payload = fetch_lean_json()

    rendered_json = render_json(payload)
    rendered_summary = render_summary(payload)

    if args.check:
        return check_drift(rendered_json, rendered_summary, args.json, args.summary)

    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(rendered_json, encoding="utf-8")
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.summary.write_text(rendered_summary, encoding="utf-8")
    print(f"Wrote storage layout JSON:    {args.json}")
    print(f"Wrote storage layout summary: {args.summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
